src/Analysis/Engine/Impl/Definitions/IModule.cs
src/Analysis/Engine/Impl/Infrastructure/PriorityProducerConsumer.cs
src/Analysis/Engine/Impl/Intellisense/AnalysisQueue.cs
src/Analysis/Engine/Impl/ModuleAnalysis.cs
src/Analysis/Engine/Test/AnalysisTest.cs
src/Analysis/Engine/Test/AstAnalysisTests.cs
src/Analysis/Engine/Test/EventTaskSources.cs
src/Analysis/Engine/Test/FluentAssertions/AssertionsFactory.cs
src/Analysis/Engine/Test/FluentAssertions/AssertionsUtilities.cs
src/Analysis/Engine/Test/FluentAssertions/CompletionItemAssertions.cs
src/Analysis/Engine/Test/FluentAssertions/CompletionListAssertions.cs
src/Analysis/Engine/Test/FluentAssertions/ModuleInfoAssertions.cs
src/Analysis/Engine/Test/FluentAssertions/ScopeAssertionsExtensions.cs
src/Analysis/Engine/Test/FluentAssertions/SignatureHelpAssertions.cs
src/Analysis/Engine/Test/FluentAssertions/VariableDefAssertions.cs
src/Analysis/Engine/Test/FluentAssertions/VariableDefAssertionsExtensions.cs
src/Analysis/Engine/Test/PriorityProducerConsumerTest.cs
src/Analysis/Engine/Test/ServerExtensions.cs
src/LanguageServer/Impl/Implementation/Server.SignatureHelp.cs
src/LanguageServer/Impl/Implementation/Server.cs
src/UnitTests/Core/Impl/TestData.cs

- Make PriorityProducerConsumer clear its queues on dispose
- Raise AnalysisQueue.AnalysisComplete at the end of consumer loop
- Derive IModule from IAnalysisValue
- Add more assertions
- Fix more tests

More test fixes and related bug fixes

---

src/Analysis/Engine/Impl/Microsoft.Python.Analysis.Engine.csproj
src/LanguageServer/Impl/Microsoft.Python.LanguageServer.csproj

trying to compile on a non-Windows platform...

use correct case for build directory

---

src/Analysis/Engine/Test/AnalysisTest.cs
src/LanguageServer/Impl/Implementation/Server.cs
src/UnitTests/Core/Impl/TestData.cs

- Avoid reparsing on the end of parsing
- Added file creation helper methods to TestData
- More tests fixed

Reparsing fix + some test work

---

src/LanguageServer/Impl/Implementation/Server.cs
src/LanguageServer/Impl/PathsWatcher.cs
src/LanguageServer/Impl/Resources.Designer.cs
src/LanguageServer/Impl/Resources.resx

Fix additional issues with paths watcher:
It was incorrectly checking for 'changed' (fix the flag check)
It gets notified on file changes in the user folder (exclude . or other non-rooted paths)
Remove notifications on 'changed', leaving deleted/added only
Add notification filter on name/directory ignoring other notifications

Fix frequent module reloading + add version banner

---

LICENSE

previously there was no year and corporation name.
Now I've added the year and corp name.

update year and corp name in license

---

src/Analysis/Engine/Test/AnalysisTest.cs

Function has multiple return types by design

Fix ParameterAnnotation tests

---

src/Analysis/Engine/Impl/Interpreter/Ast/AstModuleResolution.cs
src/Analysis/Engine/Impl/Interpreter/Ast/AstPythonInterpreter.cs
src/Analysis/Engine/Impl/Interpreter/Ast/TryImportModuleContext.cs
src/Analysis/Engine/Test/AstAnalysisTests.cs
src/LanguageServer/Impl/Implementation/Server.cs

Fixes #232 
Fixes #233 
Fixes #234
Fixes #235 
Restore lost code related to changing of user search paths

Fix Ast* tests that depends on user search path change

---

.gitignore

Formatted .gitignore file for better readability.

gitignore: Format gitignore for better readability

---

src/LanguageServer/Impl/Definitions/ITelemetryService.cs
src/LanguageServer/Impl/Implementation/ServerBase.cs
src/LanguageServer/Impl/LanguageServer.cs
src/LanguageServer/Impl/Services/TelemetryService.cs

Matching https://github.com/Microsoft/vscode-python/pull/2978

Add telemetry event structure

---

src/LanguageServer/Impl/Implementation/Server.FindReferences.cs

Fixes #302
- During walk on imports only pick names that are in range of the passed position.
- Test will have to wait until Alex' work on imports since `Find References` tests are currently tricky to make work cross modules due to issues with file load ordering and module resolution in test cases.

Fix navigation/references in module names

---

src/Analysis/Engine/Impl/Values/BuiltinFunctionInfo.cs

Restore overloads caching semantic

---

src/LanguageServer/Impl/Implementation/Server.cs

Fixes #651.
Tested in VS Code, works the same.

Fix signature trigger characters

---

src/Analysis/Ast/Impl/Modules/Definitions/IModuleCache.cs
src/Analysis/Ast/Impl/Modules/ModuleCache.cs
src/Analysis/Ast/Impl/Modules/Resolution/MainModuleResolution.cs
src/Analysis/Core/Impl/Interpreter/PythonLibraryPath.cs

Remove path cache file

---

src/Analysis/Ast/Impl/Analyzer/Symbols/FunctionEvaluator.cs
src/Analysis/Ast/Test/Microsoft.Python.Analysis.Tests.csproj
src/Core/Test/Microsoft.Python.Core.Tests.csproj
src/LanguageServer/Impl/Implementation/Server.cs
src/LanguageServer/Impl/LanguageServer.cs
src/LanguageServer/Impl/Microsoft.Python.LanguageServer.csproj
src/LanguageServer/Test/Microsoft.Python.LanguageServer.Tests.csproj
src/Parsing/Test/Microsoft.Python.Parsing.Tests.csproj
src/UnitTests/Core/Impl/UnitTests.Core.csproj

Wire up restart of analysis on changes in configuration

---

src/Analysis/Ast/Impl/Analyzer/Handlers/FromImportHandler.cs
src/Analysis/Ast/Impl/Analyzer/Handlers/ImportHandler.cs
src/Analysis/Ast/Impl/Analyzer/Handlers/StatementHandler.cs
src/Analysis/Ast/Impl/Analyzer/PythonInterpreter.cs
src/Analysis/Ast/Impl/Definitions/IPythonInterpreter.cs
src/Analysis/Ast/Impl/Extensions/MemberContainerExtensions.cs
src/Analysis/Ast/Impl/Modules/PythonModule.cs
src/Analysis/Ast/Impl/Modules/PythonPackage.cs
src/Analysis/Core/Impl/DependencyResolution/IImportSearchResult.cs
src/Analysis/Core/Impl/DependencyResolution/ImplicitPackageImport.cs
src/Analysis/Core/Impl/DependencyResolution/ModuleImport.cs
src/Analysis/Core/Impl/DependencyResolution/PathResolverSnapshot.Node.cs
src/Analysis/Core/Impl/DependencyResolution/PathResolverSnapshot.cs
src/Analysis/Core/Impl/DependencyResolution/PossibleModuleImport.cs
src/LanguageServer/Impl/Completion/ImportCompletion.cs
src/LanguageServer/Impl/Sources/DefinitionSource.cs
src/LanguageServer/Test/ImportsTests.cs

- Make modules and subpackages available for __init__.py packages
- Scope imports to module
- Fix completion in tensorflow:

Module-scoped imports

---

README.md

fix url in README

---

src/Analysis/Ast/Impl/Documents/RunningDocumentTable.cs

Log bad path and throw a cancellation instead of an argument exception

---

CONTRIBUTING.md
README.md
TROUBLESHOOTING.md

Updated wordings and links, added a troubleshooting doc.

Documentation changes

---

src/LanguageServer/Impl/Implementation/Server.cs
src/LanguageServer/Impl/Indexing/IIndexManager.cs
src/LanguageServer/Impl/Indexing/IndexManager.cs
src/LanguageServer/Test/IndexManagerTests.cs

Instead of synchronously adding workspace files to the index, do it in a separate Task.

Async adding workspace files to index

---

src/Analysis/Ast/Impl/Modules/PythonModule.cs

Fix nullref where scope is null

---

src/Analysis/Ast/Impl/Modules/PythonModule.cs

Probably overkill, but #968 doesn't appear to have been enough.

More null checks in NotifyAnalysisBegins

---

src/Analysis/Ast/Impl/Linting/UndefinedVariables/ExpressionWalker.cs
src/Analysis/Ast/Test/LintUndefinedVarsTests.cs

Walk nested suite statements in linter

---

src/LanguageServer/Impl/Python-Language-Server.nuspec

To get filenames and line numbers in user stack traces.

Don't exclude pdb files in nupkg, update URL to project

---

src/Analysis/Ast/Impl/Extensions/PythonInstanceExtensions.cs
src/Analysis/Ast/Impl/Modules/ModuleCache.cs
src/Analysis/Ast/Impl/Modules/PythonModule.cs
src/Analysis/Ast/Impl/Types/ArgumentSet.cs

Fix a few misc bugs

---

src/Analysis/Ast/Impl/Analyzer/PythonAnalyzer.cs
src/Analysis/Ast/Impl/Analyzer/PythonAnalyzerEntry.cs
src/Analysis/Ast/Impl/Dependencies/DependencyResolver.cs

Affects performance for packages with big loops. Also remove some dead code.

Reduce amount of edges in the walking graph

---

src/LanguageServer/Impl/Completion/TopLevelCompletion.cs

Fixes #1003 
Not entirely sure reason for #1003, but most probably empty analysis.

Add couple of null checks

---

src/Analysis/Ast/Impl/Extensions/ScopeExtensions.cs
src/Analysis/Ast/Impl/Linting/UndefinedVariables/ExpressionWalker.cs
src/Analysis/Ast/Test/LintUndefinedVarsTests.cs

Take into account scopes when checking definition order

---

src/Core/Impl/Extensions/IOExtensions.cs

Regression from earlier change. Old code used to create folders, new just fails. Revert to previous code but with retry.

Fix issue with writing caches

---

src/LanguageServer/Impl/Sources/DocumentationSource.cs

Fix out of bounds exception in GetFunctionParameters

---

src/Parsing/Impl/Parser.cs
src/Parsing/Test/ParserTests.cs

Add back implementation of Parser.ParseInteractiveCode.

---

src/gen.py

The final version I used in my comparisons. I have a version for the old LS on the release branch but will likely not PR it.

More gen.py updates

---

src/Analysis/Ast/Impl/Analyzer/Evaluation/ExpressionEval.Callables.cs
src/Analysis/Ast/Impl/Analyzer/Evaluation/ExpressionEval.Generics.cs
src/Analysis/Ast/Impl/Analyzer/Evaluation/ExpressionEval.Scopes.cs
src/Analysis/Ast/Impl/Analyzer/Symbols/FunctionEvaluator.cs
src/Analysis/Ast/Impl/Types/Definitions/IPythonPropertyType.cs
src/Analysis/Ast/Impl/Types/ParameterInfo.cs
src/Analysis/Ast/Impl/Types/PythonFunctionOverload.cs
src/Analysis/Ast/Impl/Types/PythonPropertyType.cs
src/Analysis/Ast/Impl/Types/PythonTypeWrapper.cs
src/Analysis/Ast/Impl/Values/Definitions/IPythonCollection.cs
src/Analysis/Ast/Impl/Values/Definitions/IPythonInstance.cs
src/Analysis/Ast/Test/GenericsTests.cs

Fixes #1163 
Code to handle standalone functions was missing.

Handle generic standalone functions

---

src/Analysis/Ast/Impl/Types/PythonFunctionOverload.cs

Port of https://github.com/microsoft/python-language-server/commit/6ceb9b817fb9c8dcf64af228bd3151eec4b18b99

Port null check for specific type creation

---

src/Core/Impl/Extensions/StringExtensions.cs
src/LanguageServer/Impl/Documentation/DocstringConverter.cs
src/LanguageServer/Test/DocstringConverterTests.cs
src/LanguageServer/Test/FluentAssertions/DocstringConverterAssertions.cs

Handle null docstrings in docstring converter

---

src/Analysis/Ast/Impl/Caching/CacheFolders.cs

Fix XDG cache path

---

src/LanguageServer/Impl/Extensibility/ICompletionExtension.cs
src/LanguageServer/Impl/Implementation/Server.Editor.cs

add ICompletionExtension2 accepting CompletionList as parameter

---

src/LanguageServer/Impl/Sources/ReferenceSource.cs

Check content for null in ScanClosedFiles

---

src/Analysis/Ast/Impl/Analyzer/PythonAnalyzerEntry.cs

Check analysis dependencies for null

---

src/Analysis/Ast/Impl/Analyzer/Symbols/ClassEvaluator.cs
src/Analysis/Ast/Test/LintInheritNonClassTests.cs

Fixing for extending something from typing module

---

src/Analysis/Ast/Impl/Analyzer/Symbols/ClassEvaluator.cs
src/Analysis/Ast/Test/LintInheritNonClassTests.cs

Not giving diagnostic message on unknown types being bases

---

src/LanguageServer/Impl/Indexing/MostRecentDocumentSymbols.cs

Fixes #1097.
The exception in #1097 is hard to pin down, but likely comes from the small window where a Document is created but is unparsed (in which case its AST is null). Since these index walkers run in their own tasks, just try a couple times with a `Task.Delay` to yield, returning an empty symbol list if the AST stays null.

Prevent crashes when the AST happens to be null

---

src/Analysis/Ast/Impl/Analyzer/Handlers/LoopHandler.cs
src/Analysis/Ast/Test/LintUndefinedVarsTests.cs

Handle else in for statement in analysis

---

src/LanguageServer/Impl/Completion/FunctionDefinitionCompletion.cs
src/LanguageServer/Test/CompletionTests.cs

When autogenerating function, do not add return for __init__

---

README.md
src/Analysis/Ast/Impl/Diagnostics/ErrorCodes.cs

Add new diagnostics to README

---

src/Analysis/Ast/Impl/Analyzer/PythonInterpreter.cs
src/Analysis/Ast/Impl/Documents/RunningDocumentTable.cs
src/Analysis/Ast/Impl/Modules/Definitions/IModuleManagement.cs
src/Analysis/Ast/Impl/Modules/Resolution/MainModuleResolution.cs
src/Analysis/Ast/Impl/Modules/Resolution/ModuleResolutionBase.cs
src/Analysis/Ast/Impl/Modules/Resolution/TypeshedResolution.cs
src/Analysis/Ast/Test/ScrapeTests.cs
src/Analysis/Core/Impl/DependencyResolution/IImportSearchResult.cs
src/Analysis/Core/Impl/DependencyResolution/ImplicitPackageImport.cs
src/Analysis/Core/Impl/DependencyResolution/ImportRoot.cs
src/Analysis/Core/Impl/DependencyResolution/PathResolver.cs
src/Analysis/Core/Impl/DependencyResolution/PathResolverSnapshot.Node.cs
src/Analysis/Core/Impl/DependencyResolution/PathResolverSnapshot.cs
src/Analysis/Core/Impl/Interpreter/ModulePath.cs
src/Analysis/Core/Impl/Interpreter/PythonLibraryPath.cs
src/Core/Impl/Collections/ImmutableArray.cs
src/Core/Impl/IO/DirectoryInfoProxy.cs
src/Core/Impl/IO/FileInfoProxy.cs
src/Core/Impl/IO/IDirectoryInfo.cs
src/Core/Impl/IO/IFileInfo.cs
src/Core/Impl/IO/PathUtils.cs
src/Core/Test/ModulePathTests.cs
src/LanguageServer/Impl/Sources/ReferenceSource.cs
src/Parsing/Test/ParserRoundTripTest.cs

- Fix the order of builtins initialization during reload
- Remove some of the dead code
- Add file size information to the module import

Merges from db

---

src/Analysis/Ast/Impl/Values/GlobalScope.cs
src/Analysis/Ast/Test/LintUndefinedVarsTests.cs
src/LanguageServer/Test/CompletionTests.cs

Adding __spec__ to builtins

---

src/Analysis/Ast/Impl/Specializations/Typing/TypingModule.cs
src/Analysis/Ast/Test/FluentAssertions/MemberAssertions.cs
src/Analysis/Ast/Test/GenericsTests.cs

Fixing partial generic params for specialized generic types

---

src/Analysis/Ast/Impl/Analyzer/Symbols/FunctionEvaluator.cs
src/Analysis/Ast/Impl/Extensions/FunctionDefinitionExtensions.cs
src/Analysis/Ast/Impl/Extensions/PythonTypeExtensions.cs

Adding null check for __init__ and __new__

---

src/Analysis/Ast/Impl/Analyzer/Handlers/SequenceExpressionHandler.cs
src/Analysis/Ast/Impl/Analyzer/Handlers/WithHandler.cs
src/Analysis/Ast/Impl/Utilities/ValueEnumerator.cs
src/Analysis/Ast/Test/LintUndefinedVarsTests.cs
src/Analysis/Ast/Test/WithTests.cs

Assign variables when using with-as construct with tuple

---

src/Analysis/Ast/Impl/Types/PythonClassType.Generics.cs
src/Analysis/Ast/Impl/Types/PythonClassType.cs

Fixes #1489 
Add lock protection to class members and bases.

Add class member lock protection

---

src/LanguageServer/Impl/Implementation/Server.cs
src/LanguageServer/Impl/Resources.Designer.cs
src/LanguageServer/Impl/Resources.resx

Log workspace root at initialization

---

src/Analysis/Ast/Impl/Extensions/NodeExtensions.cs
src/Analysis/Ast/Impl/Modules/PythonModule.cs
src/Analysis/Ast/Impl/Types/Definitions/LocationInfo.cs

Make sure location is never before (1,1)

---

src/Analysis/Ast/Test/ImportTests.cs
src/Analysis/Ast/Test/ScrapeTests.cs
src/Analysis/Core/Impl/DependencyResolution/PathResolverSnapshot.cs
src/LanguageServer/Impl/Completion/ImportCompletion.cs
src/LanguageServer/Test/CompletionTests.cs
src/Parsing/Test/ParserRoundTripTest.cs

Allow packages in GetAllImportableModuleNames

---

src/Analysis/Ast/Impl/Extensions/MemberExtensions.cs
src/LanguageServer/Impl/Completion/TopLevelCompletion.cs
src/LanguageServer/Impl/Sources/SignatureSource.cs
src/LanguageServer/Test/CompletionTests.cs

Fixes #1571 (open proper scope)
Fixes #1558 (fetch function same way signature source does)

Use proper scope when bring completion for function arguments

---

src/LanguageServer/Impl/Microsoft.Python.LanguageServer.csproj

Remove stale reference

---

src/Analysis/Ast/Impl/Caching/Definitions/IModuleDatabaseCache.cs
src/Analysis/Ast/Impl/Caching/Definitions/IModuleDatabaseService.cs
src/Analysis/Ast/Impl/Caching/Definitions/IRestoredGlobalScope.cs
src/Caching/Impl/ModuleDatabase.cs
src/LanguageServer/Impl/Implementation/Server.Custom.cs
src/LanguageServer/Impl/LanguageServer.cs
src/LanguageServer/Impl/Telemetry/RequestTimer.cs
src/LanguageServer/Test/CacheManagementTests.cs

Fixes #1579 
Extension: https://github.com/microsoft/vscode-python/pull/7689

Add command to clear analysis cache

---

.sonarcloud.properties

At https://sonarcloud.io/dashboard?id=microsoft_python-language-server.
Adding this file is all that is needed.

Added Sonar properties file to perform automated Sonar scans

---

src/Analysis/Ast/Impl/Caching/Definitions/IModuleDatabaseCache.cs
src/Analysis/Ast/Test/AnalysisTestBase.cs
src/Caching/Impl/ModuleDatabase.cs
src/Caching/Test/LibraryModulesTests.cs
src/LanguageServer/Impl/Implementation/Server.Custom.cs
src/LanguageServer/Impl/LanguageServer.Configuration.cs
src/LanguageServer/Test/CacheManagementTests.cs

Enable system library caching by default

---

src/Analysis/Ast/Impl/Analyzer/Handlers/FromImportHandler.cs
src/Analysis/Ast/Test/ImportTests.cs
src/LanguageServer/Impl/Microsoft.Python.LanguageServer.csproj

Prevent replacement of good variable value with Unknown in imports

---

src/Analysis/Ast/Impl/Analyzer/StubMerger.cs
src/LanguageServer/Impl/Microsoft.Python.LanguageServer.csproj

Discovered in test runs. Appears to be sporadic.

Fix occasional null ref in stub merge

---

src/Analysis/Ast/Impl/Microsoft-Python-Analysis.nuspec
src/Analysis/Ast/Impl/Microsoft.Python.Analysis.csproj
src/LanguageServer/Impl/Microsoft.Python.LanguageServer.csproj

Add nuspec for the analysis engine nuget feed

---

src/Analysis/Ast/Impl/Analyzer/Symbols/FunctionEvaluator.cs
src/Analysis/Ast/Test/LintNoSelfArgumentTests.cs

Check lambdas before linting on missing self/cls

---

src/Analysis/Ast/Impl/Analyzer/Evaluation/ExpressionEval.Callables.cs
src/Analysis/Ast/Impl/Analyzer/Evaluation/ExpressionEval.Constants.cs
src/Analysis/Ast/Impl/Analyzer/Handlers/FromImportHandler.cs
src/Analysis/Ast/Impl/Analyzer/PythonInterpreter.cs
src/Analysis/Ast/Impl/Analyzer/Symbols/FunctionEvaluator.cs
src/Analysis/Ast/Impl/Caching/StubCache.cs
src/Analysis/Ast/Impl/Extensions/BuiltinTypeIdExtensions.cs
src/Analysis/Ast/Impl/Modules/BuiltinsPythonModule.cs
src/Analysis/Ast/Impl/Specializations/Typing/Types/OptionalType.cs
src/Analysis/Ast/Impl/Specializations/Typing/TypingModule.cs
src/Analysis/Ast/Impl/Types/Definitions/BuiltinTypeId.cs
src/Analysis/Ast/Impl/Types/Definitions/IBuiltinPythonModule.cs
src/Analysis/Ast/Impl/Values/PythonNone.cs
src/Analysis/Ast/Impl/scrape_module.py
src/Analysis/Ast/Test/FunctionTests.cs
src/Caching/Impl/ModuleDatabase.cs
src/Caching/Impl/ModuleFactory.cs
src/LanguageServer/Impl/Completion/TopLevelCompletion.cs
src/LanguageServer/Test/CompletionTests.cs

Remove NoneType in favor of a consistent None, and remove completions which are also keywords

---

src/Analysis/Ast/Impl/Analyzer/PythonAnalyzer.cs
src/Analysis/Ast/Impl/Modules/Resolution/MainModuleResolution.cs
src/Analysis/Ast/Impl/Modules/Resolution/ModuleResolutionBase.cs
src/Analysis/Ast/Impl/Modules/Resolution/TypeshedResolution.cs
src/LanguageServer/Impl/Microsoft.Python.LanguageServer.csproj

Fixes #1418 
Also add cancellation token to path reloading.

Unify creation of analysis entries in the analyzer

---

src/LanguageServer/Impl/Sources/DocumentationSource.cs
src/LanguageServer/Test/SignatureTests.cs

Use DefaultValueString instead of DefaultValue in signature help

---

src/Analysis/Ast/Impl/Analyzer/Handlers/FromImportHandler.cs
src/Analysis/Ast/Test/LintUndefinedVarsTests.cs

Define variables in from imports when module is unresolved

---

src/Analysis/Ast/Impl/Caching/CacheService.cs
src/Analysis/Ast/Test/AnalysisTestBase.cs

in test, folder will be created when needed.
bug introduced by https://github.com/microsoft/python-language-server/pull/1722

don't check path existence in test

---

src/LanguageServer/Impl/Indexing/MostRecentDocumentSymbols.cs

If the current `_workCts` is the `cts` about to be thrown away, set it to null instead of allowing it to be re-disposed and caught by `CancelWork()`.
This almost entirely eliminates the "ObjectDisposedException" spam that fills the debug event trace when attached with VS.

Preemptively set _workCts to null

---

src/LanguageServer/Impl/CodeActions/MissingImportCodeActionProvider.cs

Fixes #1769.
Not entirely sure what condition can cause this to be null.

Fix null ref in GetAllVariables

---

src/LanguageServer/Impl/Implementation/Server.cs
src/LanguageServer/Impl/Indexing/IIndexManager.cs
src/LanguageServer/Impl/Indexing/IndexManager.cs
src/LanguageServer/Impl/Resources.Designer.cs
src/LanguageServer/Impl/Resources.resx
src/LanguageServer/Test/MissingImportCodeActionTests.cs

Defer library indexing until analysis complete or request

---

src/Analysis/Core/Impl/DependencyResolution/PathResolverSnapshot.cs

Small performance boost; a lot of time was being spent in `Contains`.
Also, don't check both lists. The old condition was roughly:
- If `x` in `A`, false.
- If `x` in `B - A`, true.
Checking the latter condition implies the former.

Pre-build set of library paths in snapshot, pass down to children

---

src/Core/Impl/Extensions/EnumerableExtensions.cs
src/LanguageServer/Impl/Indexing/SymbolIndex.cs
src/LanguageServer/Test/SymbolIndexTests.cs

Prefer exact and substring matches over fuzzy matches

---

src/Parsing/Impl/PythonLanguageVersion.cs
src/Parsing/Test/Microsoft.Python.Parsing.Tests.csproj
src/Parsing/Test/PythonVersions.cs

Declare Python 3.9
