microsoft/python-language-server

src/Analysis/Engine/Impl/Values/DictionaryInfo.cs
src/Analysis/Engine/Impl/Values/IterableInfo.cs
src/Analysis/Engine/Test/LanguageServerTests.cs

It was broken with https://github.com/Microsoft/PTVS/pull/4684 that introduced argument types to tuples. However, for basic typeless case we don't need '[]'. Alternatively, we can instead show `[]` that is base enumerable since `*a` accepts both tuples and lists.

Fix tuple args signature test

---

src/Analysis/Engine/Test/LanguageServerTests.cs
src/LanguageServer/Impl/Implementation/Server.cs

Actually looks like product bug. When adding/removing files, for dependent files we should be going through normal chain via `EnqueueItem` which does many useful things and not directly calling `AnalysisQueue.Enqueue`. We do can save on not parsing, but events should be fired and diagnostics should be updated.

Fix CompletionAfterLoad test

---

src/Analysis/Engine/Test/AnalysisTest.cs

Changed to match PTVS and PyCharm does show single parameter for `count`

Fix ListSubclassSignatures test

---

src/Analysis/Engine/Impl/AnalysisLimits.cs
src/Analysis/Engine/Impl/Interpreter/Ast/AstCachedPythonModule.cs
src/Analysis/Engine/Impl/PythonAnalyzer.cs
src/Analysis/Engine/Impl/Values/DictionaryInfo.cs
src/Analysis/Engine/Test/AstAnalysisTests.cs
src/Analysis/Engine/Test/ExpressionFinderTests.cs
src/Analysis/Engine/Test/FluentAssertions/AnalysisValueAssertions.cs
src/Analysis/Engine/Test/FluentAssertions/MemberContainerAssertions.cs
src/LanguageServer/Impl/Program.cs

```cs
analysis.Should().HavePythonModuleVariable("Package")
.Which.Should().HaveNestedModule("Module")
.Which.Should().HaveMultipleTypesMember("Class");
```
does not always apply, the structure is different in all cases. Original tests only verified actual variable members for completion.

Fix AstTypeStubPaths* tests

---

src/Analysis/Engine/Test/AnalysisTest.cs
src/Analysis/Engine/Test/AstAnalysisTests.cs

- Simplify file open, single analysis pass should be sufficient
- GetMember does not work for child packages, they are processed as special case
So reduced check to variable existence, but not members.

Fix AstTypeStubPaths* (again)

---

src/Analysis/Engine/Impl/ProjectEntry.cs
src/Analysis/Engine/Impl/PythonAnalyzer.cs
src/Analysis/Engine/Impl/Values/Definitions/IAnalysisIterableValue.cs
src/Analysis/Engine/Test/AnalysisTest.cs
src/LanguageServer/Impl/Definitions/ILanguageServerExtensionProvider.cs
src/LanguageServer/Impl/Definitions/ILogger.cs
src/LanguageServer/Impl/Implementation/AnalysisProgressReporter.cs
src/LanguageServer/Impl/Implementation/Server.Extensions.cs
src/LanguageServer/Impl/Implementation/Server.cs
src/LanguageServer/Impl/LanguageServer.cs
src/LanguageServer/Impl/Resources.Designer.cs
src/LanguageServer/Impl/Resources.resx
src/LanguageServer/Impl/Services/UIService.cs

Fixes #94 
- Make separate class for progress reporting
- Do not use 'estimate work' and rather track specific events
- Make reporting thread safe so we don't end up with multiple competing reporting tasks

Better progress reporting

---

src/Analysis/Engine/Impl/LanguageServer/Enums.cs
src/Analysis/Engine/Impl/LanguageServer/Extensibility.cs
src/Analysis/Engine/Impl/LanguageServer/ILanguageServerExtension.cs
src/Analysis/Engine/Impl/LanguageServer/ILanguageServerExtensionProvider.cs
src/Analysis/Engine/Impl/LanguageServer/IServer.cs
src/Analysis/Engine/Impl/LanguageServer/Server.cs
src/Analysis/Engine/Impl/LanguageServer/Structures.cs
src/Analysis/Engine/Impl/ModuleAnalysis.cs
src/LanguageServer/Impl/Implementation/Server.Completion.cs
src/LanguageServer/Impl/Implementation/Server.Extensions.cs
src/LanguageServer/Impl/Implementation/Server.cs
src/LanguageServer/Impl/Program.cs

- Declare old IServer
- Implement IServer stub 
- Implement thunk down to the old type of completion handling
Also fixed #26 by removing the command. IC extension is registering its own command, we do not handle this one anyway.

Extensions backward compatibility

---

src/Analysis/Engine/Impl/Definitions/IProjectEntry.cs
src/Analysis/Engine/Impl/Interpreter/Ast/AstPythonModule.cs
src/Analysis/Engine/Impl/ProjectEntry.cs
src/Analysis/Engine/Test/AnalysisTest.cs
src/LanguageServer/Impl/Definitions/IPythonLanguageServer.cs
src/LanguageServer/Impl/Implementation/CompletionAnalysis.cs
src/LanguageServer/Impl/Implementation/ProjectFiles.cs
src/LanguageServer/Impl/Implementation/Server.WorkspaceSymbols.cs
src/LanguageServer/Impl/Implementation/Server.cs

And few more useful things to extensibility interfaces

Add ability to get document content from API

---

src/Analysis/Engine/Impl/Definitions/IModuleAnalysis.cs
src/Analysis/Engine/Impl/ModuleAnalysis.cs
src/Analysis/Engine/Impl/ProjectEntry.cs
src/Analysis/Engine/Test/AnalysisTest.cs
src/Analysis/Engine/Test/LanguageServerTests.cs
src/Analysis/Engine/Test/ServerExtensions.cs
src/Analysis/Engine/Test/ThreadingTest.cs
src/LanguageServer/Impl/Implementation/AnalysisProgressReporter.cs
src/LanguageServer/Impl/Implementation/CompletionAnalysis.cs
src/LanguageServer/Impl/Implementation/EditorFiles.cs
src/LanguageServer/Impl/Implementation/ParseQueue.cs
src/LanguageServer/Impl/Implementation/ProjectFiles.cs
src/LanguageServer/Impl/Implementation/Server.FindReferences.cs
src/LanguageServer/Impl/Implementation/Server.WorkspaceSymbols.cs
src/LanguageServer/Impl/Implementation/Server.cs
src/LanguageServer/Impl/Implementation/ServerBase.cs
src/LanguageServer/Impl/LanguageServer.Lifetime.cs
src/LanguageServer/Impl/LanguageServer.cs
src/LanguageServer/Impl/PathsWatcher.cs
src/LanguageServer/Impl/Services/IdleTimeTracker.cs

Fixes #111 
- Improves #109 - avoid reloading modules on any configuration change. Still need to debug why reloading modules leaks.
- Improves test stability as well as Rename/FindReferences/DocumentSymbols/GotoDefinition by waiting for the complete analysis.

Fix wait for analysis complete, fix tests and avoid reload on all config changes

---

src/Analysis/Engine/Impl/ModuleAnalysis.cs
src/Analysis/Engine/Test/AnalysisTest.cs

Fix References_Parameters_NestedFunction

---

src/Analysis/Engine/Test/AnalysisTest.cs

To match PTVS original https://github.com/Microsoft/PTVS/blob/master/Python/Tests/Analysis/AnalysisTest.cs#L3133-L3135

Fix ReferencesGeneratorsV2 test

---

src/Analysis/Engine/Impl/Analyzer/FunctionAnalysisUnit.cs
src/Analysis/Engine/Impl/Values/SpecializedNamespace.cs
src/Analysis/Engine/Test/InheritanceTests.cs
src/Analysis/Engine/Test/Microsoft.Python.Analysis.Engine.Tests.csproj

This adds a test for the analysis of return values of abstract properties (properties, marked with `@abc.abstractproperty`).
This also adds a partial fix for it not being analyzed properly. (related to #115)
Unfortunately, due to some regression (?) between PTVS/master and python-language-server/master, this does not seem to be enough: test variable `b` analysis results in two possible return values, `int` (correct) and `A.virt` (which is incorrect, and eventually resolves to be `Unknown`). The later seems to be happening because on the first pass `ddg._eval.Evaluate(@abc.abstractproperty)` results in empty set.

A test to ensure @abc.abstractproperty return value is analyzed correctly

---

src/Analysis/Engine/Test/LineFormatterTests.cs
src/LanguageServer/Impl/Implementation/LineFormatter.cs

I thought of this case while reading the fstring spec. The line formatter defaults to not spacing around string literals, but it's likely better to insert a space between two string literals next to each other.
For reference:
- autopep8 leaves spacing as-is, so `'a''b'` and `'a' 'b'` would not be changed (even with more than one space between). I could emulate this behavior in the line formatter, since `TokenExt` includes `PreceedingWhitespace`.
- yapf ensures there is a space between two strings.
- black behaves the same as yapf (barring its replacement of `'` with `"`).

Fix string concatenation spacing in line formatter

---

src/LanguageServer/Impl/PathsWatcher.cs

Fix additional issues with paths watcher:
- It was incorrectly checking for 'changed' (fix the flag check)
- It gets notified on file changes in the user folder (exclude `.` or other non-rooted paths) 
- Remove notifications on 'changed', leaving deleted/added only
- Add notification filter on name/directory ignoring other notifications

RELEASE: Fix frequent module reloading

---

src/Analysis/Engine/Impl/AnalysisSet.cs
src/Analysis/Engine/Impl/OverloadResult.cs
src/Analysis/Engine/Impl/Resources.Designer.cs
src/Analysis/Engine/Impl/Resources.resx
src/Analysis/Engine/Impl/Values/BuiltinInstanceInfo.cs
src/Analysis/Engine/Impl/Values/ClassInfo.cs
src/Analysis/Engine/Impl/Values/FunctionInfo.cs
src/Analysis/Engine/Impl/Values/InstanceInfo.cs
src/Analysis/Engine/Impl/Values/Protocols.cs
src/Analysis/Engine/Test/TypeAnnotationTests.cs

- Make type overloads use same way of generating parameter types as tooltip/hover. This way get get proper short types and not something like `a:T, int` on a generic or `a:list[float, float, float], list[float]`.
- Return value should not have `[ ]` around it if it is a single type.
- If function returns nothing, then display `None` and not `[ ]`
- Prettify documentation with proper spacing
- Update all TypingModuleDocumentation* tests baselines

Fix type annotation on overloads

---

src/Analysis/Engine/Impl/Interpreter/Ast/AstAnalysisFunctionWalker.cs

Looks like return types may end up containing nulls. For example, GetValueFromExpression can return null.
The crash was in ReturnType => ReturnTypes.Where(v => v.TypeId...)

Fix null reference

---

src/LanguageServer/Impl/Implementation/Server.cs

This is a hot fix to avoid infinite queuing of modules for analysis.

RELEASE: Remove requeue of dependent modules

---

src/LanguageServer/Impl/LanguageServer.cs
src/LanguageServer/Impl/PathsWatcher.cs

- Apparently new code was never called. Old code remained despite new function exists.
- Fix issue in throttling

RELEASE: Restore path watching fix lost in merges

---

src/.editorconfig

Added .editorconfig in addition to,  omnisharp.json as, .editorconfig is supported more widely.

Add .editorconfig file in addition to omnisharp.json #132

---

src/Analysis/Engine/Impl/ModuleAnalysis.cs
src/Analysis/Engine/Test/AnalysisTest.cs
src/Analysis/Engine/Test/AstAnalysisTests.cs

Fixes #40 
Code is pretty confusing, with reassignments and import names same as variable names. Various apps behave differently. Basically the fix is
- Keep any reference to external files as definition (so use can navigate there)
- Keep `import abc` as reference (so use can find all usages of 'abc').

Fix References_GrammarTest_Statements

---

src/Analysis/Engine/Impl/Analyzer/FunctionAnalysisUnit.cs
src/Analysis/Engine/Impl/Values/Definitions/IFunctionInfo.cs
src/Analysis/Engine/Impl/Values/FunctionInfo.cs

Adds `IsAbstract` property to `IFunctionInfo` and `FunctionInfo`, that tells if the function is abstract or not.
Note: should we consider using tri-state `bool?` here? During analysis, until all decorators are analyzed, `IsAbstract` may return `false`, when the final analysis result will be `true` (it is the case right now, as in many cases imports of `abc` are processed after functions).

mark abstract functions as such

---

src/Analysis/Engine/Test/AnalysisTest.cs
src/Analysis/Engine/Test/CompletionTest.cs
src/Analysis/Engine/Test/FluentAssertions/CompletionListAssertions.cs
src/Analysis/Engine/Test/LanguageServerTests.cs
src/Analysis/Engine/Test/ServerExtensions.cs
src/Analysis/Engine/Test/ServerTestMethodAttribute.cs
src/LanguageServer/Impl/Definitions/ServerSettings.cs
src/LanguageServer/Impl/Implementation/CompletionAnalysis.cs
src/LanguageServer/Impl/Implementation/Server.Completion.cs
src/LanguageServer/Impl/LanguageServer.cs
src/UnitTests/Core/Impl/TestEnvironmentImpl.cs

Also contains some test infrastructure improvements.

Fix issue #35: `AddBrackets` functionality not working when using new analysis engine in VSC

---

src/Analysis/Engine/Impl/Values/Protocols.cs

Fixes #173
Tuple protocols are compared by name which makes tuples with different types the same, which causes trouble in analysis hash set when it merges types of function parameters in overloads.

Make tuples with different arguments different types

---

src/Analysis/Engine/Impl/Infrastructure/Extensions/StringBuilderExtensions.cs
src/Analysis/Engine/Impl/Values/Protocols.cs

Additional fix for https://github.com/Microsoft/python-language-server/issues/173 since 'SelectMany' drops empty sequences and tuples lose arguments of unknown type making them look like they have fewer arguments.

Make sure tuple protocol name does not ignore unknown parameter types

---

src/Analysis/Engine/Impl/Interpreter/Ast/AstAnalysisWalker.cs
src/Analysis/Engine/Impl/Interpreter/Ast/AstBuiltinsPythonModule.cs
src/Analysis/Engine/Impl/Interpreter/Ast/AstModuleCache.cs
src/Analysis/Engine/Impl/Interpreter/Ast/AstModuleResolution.cs
src/Analysis/Engine/Impl/Interpreter/Ast/AstPythonInterpreter.cs
src/Analysis/Engine/Impl/Interpreter/Ast/AstPythonInterpreterFactory.cs
src/Analysis/Engine/Impl/Interpreter/Ast/AstScrapedPythonModule.cs
src/Analysis/Engine/Impl/Interpreter/Ast/TryImportModuleContext.cs
src/Analysis/Engine/Impl/Interpreter/Ast/TryImportModuleResult.cs
src/Analysis/Engine/Impl/Interpreter/Definitions/IPythonInterpreterFactory.cs
src/Analysis/Engine/Impl/ModuleTable.cs
src/Analysis/Engine/Impl/PythonAnalyzer.cs
src/Analysis/Engine/Test/AnalysisTest.cs
src/Analysis/Engine/Test/AstAnalysisTests.cs
src/LanguageServer/Impl/Implementation/Server.cs
src/LanguageServer/Impl/Resources.Designer.cs
src/LanguageServer/Impl/Resources.resx

Import work prep
- Remove duplication of imported modules between factory and interpreter
- Move resolution code into a separate class
- Move caching code into its own class
Otherwise no logic change

Clean up factory/interpreter: split importing code

---

Using_in_sublime_text.md

This pull request add a single markdown file with instructions on how to configure SublimeText with the LSP plugin for using the Microsoft Python Language Server

Added instructions for using in SublimeText with the LSP plugin

---

src/Analysis/Engine/Test/BlockFormatterTests.cs
src/Analysis/Engine/Test/LanguageServerTests.cs
src/LanguageServer/Impl/Implementation/BlockFormatter.cs
src/LanguageServer/Impl/Implementation/Server.OnTypeFormatting.cs
src/LanguageServer/Impl/Implementation/Server.cs
src/UnitTests/TestData/Formatting/elseBlocks2.py
src/UnitTests/TestData/Formatting/elseBlocks4.py
src/UnitTests/TestData/Formatting/elseBlocksFirstLine2.py
src/UnitTests/TestData/Formatting/elseBlocksFirstLine4.py
src/UnitTests/TestData/Formatting/elseBlocksFirstLineTab.py
src/UnitTests/TestData/Formatting/elseBlocksTab.py
src/UnitTests/TestData/Formatting/tryBlocks2.py
src/UnitTests/TestData/Formatting/tryBlocks4.py
src/UnitTests/TestData/Formatting/tryBlocksTab.py

Updates #165.
This is a 1:1 port of the `:` triggered block formatter that's running in the extension, including its tests. See here for the current implementation:
- https://github.com/Microsoft/vscode-python/blob/master/src/client/typeFormatters/codeBlockFormatProvider.ts
- https://github.com/Microsoft/vscode-python/blob/master/src/client/typeFormatters/blockFormatProvider.ts
- https://github.com/Microsoft/vscode-python/blob/master/src/client/typeFormatters/contracts.ts
This may not be the most efficient or most correct way to do this sort of formatting, but not having any block formatting in PLS means that we can't also ship the line formatting code. This will at least behave the same way and let us ship the new line formatter without regressing the editor in terms of features. This …

Port regex-based block formatting from vscode-python

---

src/Analysis/Engine/Test/LanguageServerTests.cs

Bisected the failing `CompletionForOverrideArgs` test back to #176. `super()` shouldn't be getting called with args here.

Fix function override completion test

---

src/Analysis/Engine/Test/LanguageServerTests.cs
src/LanguageServer/Impl/Implementation/CompletionAnalysis.cs

Fixes #236.
This also improves the completed override function by not repeating default values, instead referring to parameters directly.
Old behavior:
New behavior:
This also removes the "safe" check for variable names, as I think all it seems to actually do is prevent non-ASCII identifiers from working (which are [allowed in Python 3](https://docs.python.org/3/reference/lexical_analysis.html#identifiers)).

Fix function override completion test, improve behavior

---

src/Analysis/Engine/Test/AnalysisTest.cs
src/Analysis/Engine/Test/FindReferencesTests.cs
src/Analysis/Engine/Test/FluentAssertions/ScopeAssertions.cs
src/Analysis/Engine/Test/LanguageServerTests.cs
src/Analysis/Engine/Test/ReferencesTests.cs
src/Analysis/Engine/Test/ServerBasedTest.cs

- Following changes to the 1/0 based location output.
- Move reference tests to a separate class (part of https://github.com/microsoft/python-language-server/issues/225)

Update FindReferences baseline

---

src/Analysis/Engine/Impl/Infrastructure/Check.cs
src/Analysis/Engine/Impl/Parsing/Parser.cs
src/Analysis/Engine/Test/CompletionTest.cs
src/Analysis/Engine/Test/PythonVersions.cs
src/Analysis/Engine/Test/ServerTestMethodAttribute.cs
src/LanguageServer/Impl/Implementation/CompletionAnalysis.cs
src/LanguageServer/Impl/Implementation/LineFormatter.cs
src/LanguageServer/Impl/Implementation/Server.Completion.cs

This PR also contains big refactoring of `CompletionAnalysis`:
- Non-intersecting code paths are separated
- Control flow is separated from actual completion items
- Nesting reduced

Fix #241: addBrackets adds parens to function override completions

---

src/LanguageServer/Impl/Implementation/Server.cs

No unit-test, bug repro requires call to `pip install`

Fix #209: Reloading modules does not clear import warnings or intellisense

---

src/Analysis/Engine/Impl/Analyzer/ExpressionEvaluator.cs
src/Analysis/Engine/Impl/Values/InstanceInfo.cs

Fixes #263.
Updates #242.
This PR removes an incorrect check for undeclared variables, and disables (for now) the messages when the analyzer isn't certain something is callable.
In a future change to help with #242 and #19, these sorts of checks won't directly add a diagnostic to be displayed in the editor, instead adding them in with the other analysis to then be filtered/displayed and have code actions related to them.
Note that this has no visible change, as the diagnostics don't have any tests associated with them, nor are they visible to users since VS Code doesn't send `python.liveLinting` in the capabilities. We'll update this in the future to deal with editor settings/pylintrc/etc.

Remove or disable bad diagnostics for now

---

src/Analysis/Engine/Impl/Parsing/PythonLanguageVersion.cs
src/Analysis/Engine/Test/AnalysisTest.cs
src/Analysis/Engine/Test/AstAnalysisTests.cs
src/Analysis/Engine/Test/MutateStdLibTest.cs
src/Analysis/Engine/Test/PythonVersions.cs

Fixes #268
- Add 3.7 and 3.8 to available versions
- Add 3.7 and 3.8 to the full std library test
- Remove tests dedicated to 3.1 - 3.4

Clean Python versions in tests

---

src/Analysis/Engine/Test/ParserRoundTripTest.cs

#271 had a few leftover references to the removed Python versions, preventing tests from building.

Remove references to removed test versions in ParserRoundTripTests

---

src/.editorconfig
src/Analysis/Engine/Impl/Analyzer/DDG.cs
src/Analysis/Engine/Impl/Values/FunctionInfo.cs
src/Analysis/Engine/Test/InheritanceTests.cs

Adds a set of derived functions to `FunctionInfo`. Fills the set when `DDG` encounters a `FunctionDefinition`.
Whenever a call to some function is analyzed, it looks at the list of derived functions, and passes the call info along to them.
Also added some styles to .editorconfig
Fixes #194 .
Seems to reduce the total number of failing test cases (local run shows 32->29).
I could not understand if I needed to also requeue anything for analysis. Left a comment about it in the code.
The change might be incomplete, as the new code was not added to the case when `_callsWithClosure != null` in `FunctionInfo.Call`. I could not quickly understand that code.

Propagate known parameter types to derived functions

---

src/Analysis/Engine/Impl/OverloadResult.cs

Fix null reference in OverloadResultComparer

---

src/Analysis/Engine/Impl/Values/InstanceInfo.cs

Subj.
When there are no instance attributes, `InstanceAttributes` should return `null` or an empty dictionary. In this change I choose to return `null`

Fixes NullReferenceException when trying to access InstanceInfo.InstanceAttributes

---

src/Analysis/Engine/Test/CompletionTests.cs
src/LanguageServer/Impl/Implementation/Server.Completion.cs

Fixes #23 
- With whitespace surrounding dot span of the expression can be to the right of the dot. Adjust span accordingly.
- Add test for the case (reproes only when completion context is supplied)

Fix ApplicableSpan calculation

---

src/Analysis/Engine/Test/LanguageServerTests.cs
src/LanguageServer/Impl/Definitions/ServerSettings.cs
src/LanguageServer/Impl/Implementation/Server.cs
src/LanguageServer/Impl/LanguageServer.cs

Fixes #242.
#289 causes a few issues to do with parser-generated diagnostics, and there are more diagnostics I wasn't aware of coming from ErrorSink. This is a simplified PR that does the minimum to enable diagnostics (ignoring "Unspecified" at publish time) and fixes the setting change bug.
We'll have to revisit where diagnostics should be stored to access via code actions in a different PR. There are only two diagnostics that actually come out of the server which can be disabled with `python.analysis.disabled` for now.
I'll close #289 in favor of this one.

Only enable diagnostics and fix settings change detection

---

src/Analysis/Engine/Impl/AnalysisLimits.cs
src/Analysis/Engine/Impl/Analyzer/DDG.cs
src/Analysis/Engine/Impl/Values/FunctionInfo.cs
src/Analysis/Engine/Test/InheritanceTests.cs

It is similar #194, in that the same types parameter types might be OK for base methods. It could happen when we just don't have any examples in the current code, that would give that kind of information to analyzer.
By default set to `false` to keep conservative behavior.
```python
class Base:
def foo(x):
...
class Derived(Base):
def foo(x):
...
Derived().foo(42)
```

Added an option to propagate parameter types to base methods

---

src/Analysis/Engine/Impl/Documentation/DocumentationBuilder.cs
src/Analysis/Engine/Test/CompletionTests.cs
src/Analysis/Engine/Test/HoverTests.cs
src/LanguageServer/Impl/Implementation/CompletionAnalysis.cs

Fixes #305.
I opted to move this up into DocumentationBuilder. Hover seems to avoid this problem as it's able to use the helper method `GetMarkupContent`, which ensures that the kind is set properly.
Completion documentation generation lives in `CompletionAnalysis`, and seems to be the only user of `preferredFormat`. Before merging this PR, I'm going to investigate and see how much trouble it'd be to rework doc generation into using the capability-sent list of supported MarkupKinds, so I've marked this as [WIP] for now.

[WIP] Ensure DocumentationBuilder never has a null preferred MarkupKind

---

src/Analysis/Engine/Test/CompletionTests.cs

Fixes #310
Somehow backslashes creeped back in.

Fix TopLevelCompletions test on Mac

---

src/Analysis/Engine/Impl/Analyzer/ErrorMessages.cs
src/Analysis/Engine/Impl/Analyzer/ExpressionEvaluator.cs
src/Analysis/Engine/Impl/PythonAnalyzer.cs
src/Analysis/Engine/Impl/Resources.Designer.cs
src/Analysis/Engine/Impl/Resources.resx
src/Analysis/Engine/Test/LanguageServerTests.cs
src/LanguageServer/Impl/Implementation/ParseQueue.cs

Closes #299. (Specifically the naming part in the comments.)
Strings have been moved into Resources. `(parser)` and `(analysis)` have been removed from the diagnostic source strings. I also renamed one of the codes to be more representative of what it actually means (while we have the ability to change something like this without breaking users).
The tests I modified in LanguageServerTests are not well-written (hardcoded strings rather than a table of actual things to compare), but I just made them pass for now and could fix them later.

Resource-ify diagnostic messages, rename some codes, remove "(...)"

---

src/.editorconfig

Not having one seems to break sonar (plus arguably sources files should do this anyway).
This doesn't seem to fix it in VS from what I can tell (even with Format Document), but does work in VS Code with the EditorConfig extension.

Modify editorconfig to add newline to end of files

---

src/Analysis/Engine/Impl/Analyzer/ExpressionEvaluator.cs
src/Analysis/Engine/Test/LanguageServerTests.cs

Fixes #335.
I'm not sure if it's good or bad that a `ConstantExpression` is making it into `LookupAnalysisSetByName`, but checking for it before warning will prevent user-visible weirdness.

Fix None being reported as not defined in type hints

---

src/Analysis/Engine/Test/CompletionTests.cs
src/Analysis/Engine/Test/FluentAssertions/CompletionItemAssertions.cs
src/LanguageServer/Impl/Implementation/CompletionAnalysis.cs
src/LanguageServer/Impl/Implementation/Server.Completion.cs

Fixes #342.
All places where `insertText` is set, `insertTextFormat` is now also set. Tests which check `insertText` directly also now check `insertTextFormat`. Most tests use AssertCompletion, which I have modified to also check that every matching completion has a specific format. VS complains about the tuple because I used `Item#` instead of an inferred name to access it, which I'd like to do but cannot because this project seems to only be on C# 7.0, not 7.1.
I think it would be better for the classes that use these sorts of enums to explicitly define the default value (especially given so many LSP enums do not contain 0), but there are quite a few enums and a load of duplication in the two Structures.cs files that I'm not going to try to attempt it now.

Fix invalid insertTextFormat in CompletionItem instances

---

src/Analysis/Engine/Impl/AnalysisLimits.cs
src/Analysis/Engine/Impl/AnalysisValue.cs
src/Analysis/Engine/Impl/Analyzer/InterpreterScope.cs
src/Analysis/Engine/Impl/Values/IterableInfo.cs
src/Analysis/Engine/Impl/Values/Protocols.cs
src/Analysis/Engine/Test/AnalysisTest.cs

Fixes #50
- Recursive tuples analysis produced huge description string. Limit that.
- Reduce number of stored types (we don't really need to store various combinations of arguments and return types at all, but that's a different issue).

Fix max length of short descriptions and tuple names

---

src/Analysis/Engine/Impl/Parsing/Parser.cs
src/Analysis/Engine/Impl/Values/TypingModuleInfo.cs
src/Analysis/Engine/Test/AnalysisTest.cs

Fix crash when TypeVar has no arguments

---

src/LanguageServer/Impl/TelemetryRpcTraceListener.cs

This class of exceptions gets thrown a lot, and should't be recorded.

Ignore LanguageServerException in telemetry

---

src/Analysis/Engine/Impl/PythonAnalyzer.cs

It's causing some InvalidOperationExceptions to be thrown. Disable this for now, since we're not yet using this system.

Remove call to path resolver until it's finished

---

src/LanguageServer/Impl/Services/TelemetryService.cs
src/LanguageServer/Impl/Telemetry.cs
src/LanguageServer/Impl/TelemetryRpcTraceListener.cs

Fixes #373.
The "default" version for the assembly is 1.0.0.0 (which shows up when running a locally built copy), so I've added the suffix `-debug` when `DEBUG` is set in order to distinguish events if we reach a 1.0.0.0 release.

Include assembly version number in telemetry event properties, standardize TelemetryEvent creation

---

src/Analysis/Engine/Impl/AnalysisUnit.cs
src/Analysis/Engine/Test/LanguageServerTests.cs

Fixes #387.
I'm not sure why the old code modified `ddg.Scope`. I'm not a DDG expert yet, but this is the only place where the scope gets explicitly changed by something other than the DDG class itself, which feels wrong (especially given that it doesn't put it back the way it was, instead changing it to some other scope entirely).
The code I'm removing was added in: https://github.com/Microsoft/PTVS/commit/861e1e4e3559d165615631733cfc3953292a52ff#diff-20d37dda723b616a828c08df50fc739b
If I'm missing something obvious here, let me know.

Don't modify the DDG scope when analyzing the comprehension

---

src/Analysis/Engine/Test/LineFormatterTests.cs
src/LanguageServer/Impl/Implementation/LineFormatter.cs
src/LanguageServer/Impl/Implementation/Server.OnTypeFormatting.cs
src/LanguageServer/Impl/Resources.Designer.cs
src/LanguageServer/Impl/Resources.resx

Fixes #388.
Instead of throwing a generic exception, keep track of the unmatched token for later use, and just ignore it. When the line formatting is done, DocumentOnTypeFormatting can check to see if an unmatched token occurred before or in the line being formatted and report to the user a warning about the bad behavior.
I also fixed the comment strings that claimed that the line formatter worked with one-indexed lines, which is no longer true after Alex's changes to this code.

Improve line formatter behavior with unmatched close brackets, log warning

---

src/Analysis/Engine/Impl/Values/ProtocolInfo.cs
src/Analysis/Engine/Impl/Values/SpecializedNamespace.cs

Fixes #449.
Also fixes an ArgumentNullException in a dictionary TryGetValue in ProtocolInfo. I'm not sure why that one is happening, but it's also showing up as frequently as the SpecializedNamespace issue.

Fix nullref in SpecializedNamespace and arg-null ProtocolInfo dict access

---

src/Analysis/Engine/Test/AnalysisTest.cs

There was a typo which prevented the tests from building.

Fix typo in TestPackageImportStar3X

---

src/Analysis/Engine/Impl/DependencyResolution/PathResolverSnapshot.cs
src/Analysis/Engine/Impl/PythonAnalyzer.cs
src/Analysis/Engine/Test/ImportTests.cs
src/Analysis/Engine/Test/ServerExtensions.cs

Fix #281: Support "go to definition" for namespace packages
Fix #466: Fix "go to definition" and resolving imports
The fix is to put user search paths in front of workspace directory so that modules inside extra paths can be used as roots for packages

Fix for extra paths inside workspace

---

src/Analysis/Engine/Impl/PythonAnalyzer.cs

Fixes #470 
Cached value may or may not be a class info. Previous calls to `GetAnalysisValueFromObjects` may have cached a different object for the type. For example, `IPythonFunction` would cache `BuiltinFunctionInfo` and not `BuiltinClassInfo`.
Before https://github.com/Microsoft/python-language-server/pull/439 it worked since `IPythonFunction` and `IPythonClass` were not `IPythonType` and in `GetAnalysisValueFromObjects` `IPythonType` was handled first so the cache would always contain item created for `IPythonType` as the first in the order of processing. This is no longer true. 
The fix is not ideal, another approach is to create different caches for different types.

Fix invalid cast in GetBuiltinType

---

src/Analysis/Engine/Impl/Intellisense/AnalysisQueue.cs
src/Analysis/Engine/Impl/Values/BuiltinNamespace.cs
src/Analysis/Engine/Impl/Values/SpecializedNamespace.cs
src/LanguageServer/Impl/LanguageServer.Lifetime.cs
src/LanguageServer/Impl/LanguageServer.cs

Fixes #448.
Fixes #463.
Fixes #440. (I didn't realize `?` would short circuit. Found all mistakes with `rg '\w+(\(\))?\?\.\w+\.Maybe'`)
Also fixes the nullrefs coming from Shutdown.
Opening this PR into `release`, but I can easily switch it to `master` (since they're even).
There is one TODO I'd like feedback on, for the fix to #448.

Fix various common exceptions, log on a failed directory load

---

src/Analysis/Engine/Impl/AnalysisHashSet.cs
src/Analysis/Engine/Impl/AnalysisSet.cs
src/Analysis/Engine/Impl/Intellisense/AnalysisQueue.cs
src/Analysis/Engine/Impl/LocationInfo.cs
src/Analysis/Engine/Impl/OverloadResult.cs
src/Analysis/Engine/Impl/PythonAnalyzer.cs
src/Analysis/Engine/Impl/Values/ClassInfo.cs

This isn't a complete fix, but does seem to improve #495 in some cases. Adds back the early MRO return removed in #277, so now large class hierarchies won't over-propagate types (where some of the trouble with fastai happens do to the Transform class). I also optimized AnalysisHashSet a little to do length checks when possible.
There are still times when things get caught up comparing unions for a while, but it seems to be nondeterministic.

Mitigate some of #495 via MRO member selection and analysis set optimization

---

src/Analysis/Engine/Impl/Analyzer/DDG.cs
src/Analysis/Engine/Impl/DependencyResolution/NoKnownParentPackage.cs
src/Analysis/Engine/Impl/DependencyResolution/PathResolverSnapshot.cs
src/Analysis/Engine/Impl/Infrastructure/Extensions/StringExtensions.cs
src/Analysis/Engine/Impl/Resources.Designer.cs
src/Analysis/Engine/Impl/Resources.resx
src/Analysis/Engine/Test/AddTestSpecificSearchPathAttribute.cs
src/Analysis/Engine/Test/EventTaskSources.cs
src/Analysis/Engine/Test/ImportTests.cs
src/Analysis/Engine/Test/ServerTestMethodAttribute.cs

- Fix #509: PLS doesn't flag error in a relative import if it is found in another root directory
- Fix #510: PLS doesn't resolve relative paths correctly

Two path resolution bug fixes

---

src/Analysis/Engine/Impl/Interpreter/Ast/AstModuleResolution.cs

Fixes #522.
Did this quick this morning, figured I'd PR instead of letting it sit around.
@AlexanderSher 	Curious how you'd test this. Tried my hand for a bit but couldn't easily see a way to trigger this. I wanted to spawn a server, add a file in the test-specific root, then delete it, and then call `ImportModuleAsync` to see that I get ModuleNotFound, but I don't think I had the search paths setup correctly. Feel free to absorb this into a different PR if it's easier.

Catch exceptions when importing from search paths

---

src/Analysis/Engine/Impl/Definitions/Diagnostic.cs
src/Analysis/Engine/Impl/DependencyResolution/PathResolverSnapshot.cs
src/Analysis/Engine/Impl/PythonAnalyzer.cs
src/Analysis/Engine/Test/LanguageServerTests.cs
src/LanguageServer/Core/Impl/Definitions/ServerSettings.cs
src/LanguageServer/Core/Impl/Implementation/DiagnosticsErrorSink.cs
src/LanguageServer/Impl/LanguageServer.cs
src/PTVS/Microsoft.PythonTools.Analyzer/Impl/Intellisense/AnalysisProtocol.cs
src/PTVS/Microsoft.PythonTools.Analyzer/Impl/Intellisense/OutOfProcProjectAnalyzer.cs
src/PTVS/Microsoft.PythonTools.Analyzer/Impl/python-language-server-ptvs.nuspec

- Fix nuspec folder
- Fix PTVS issue #5026: Imported packages remain unresolved once a new environment is finished being created

Fix couple of bugs

---

src/LanguageServer/Impl/Program.cs

I'm submitting this since I had it sitting around. Let me know what you think.
This was suggested in #479. Doing this lowers the priority of the process to "below normal", which on UNIX-y systems is implemented as nice level 10. It may help yield CPU time to other things on the system if the analyzer is stuck somewhere using 100% of a core.
I checked the Roslyn analyzer after noticing it was set to below normal priority in my process list ([see here](https://github.com/dotnet/roslyn/blob/fab7134296816fc80019c60b0f5bef7400cf23ea/src/Workspaces/Remote/ServiceHub/Services/RemoteHostService.cs#L83-L89)), hence this PR. They additionally have the notion of a "[user operation booster](https://github.com/dotnet/roslyn/blob/fab7134296816fc80019c60b0f5bef7400cf23ea/src/Workspaces/Remote/ServiceHub/ …

Set process priority to "below normal"

---

src/Core/Impl/Extensions/StringExtensions.cs
src/LanguageServer/Impl/Documentation/DocstringConverter.cs
src/LanguageServer/Impl/Documentation/DocumentationExtensions.cs
src/LanguageServer/Impl/Implementation/Server.cs
src/LanguageServer/Impl/Sources/MarkdownDocumentationSource.cs
src/LanguageServer/Test/DocstringConverterTests.cs
src/LanguageServer/Test/FluentAssertions/DocstringConverterAssertions.cs

Closes #548.
Still missing Google/Numpy style param/return/etc list parsing. I'm also not too happy with the code duplication in the markdown documentation source.

Docstring converter

---

src/LanguageServer/Impl/Sources/SignatureSource.cs

Fixes #614.
Pulled this from the old LS; it wasn't carried over.

Fix empty signature tooltip after function call

---

src/Parsing/Impl/Parser.cs
src/Parsing/Test/ParserTests.cs
src/UnitTests/TestData/Grammar/IncompleteMemberExpr.py

Fixes #345 
If next token is a new line after dot, squiggle the dot instead.

Don't  squiggle new lines after incomplete member expression

---

src/Analysis/Ast/Test/InheritanceTests.cs

Grabbing this test for completeness' sake.

Port test from #312 to new analysis

---

src/Analysis/Ast/Impl/Analyzer/Evaluation/ExpressionEval.Scopes.cs
src/Analysis/Ast/Impl/Analyzer/ModuleWalker.cs
src/Analysis/Ast/Impl/Extensions/PythonTypeExtensions.cs
src/Analysis/Ast/Impl/Modules/PythonModule.cs
src/Analysis/Ast/Impl/Types/Definitions/IPythonClassMember.cs
src/Analysis/Ast/Impl/Types/Definitions/IPythonClassType.cs
src/Analysis/Ast/Impl/Types/Definitions/IPythonModule.cs
src/Analysis/Ast/Impl/Types/PythonFunctionType.cs
src/Analysis/Ast/Impl/Types/PythonType.cs
src/LanguageServer/Impl/Sources/DefinitionSource.cs
src/LanguageServer/Test/GoToDefinitionTests.cs

Fixes #618
* If goto def happens in import statement, open module source
* Resolve location to original module if it is a stub
* Transfer location for stubbed types so we can navigate to them in the real module
* Fix incorrect fetching of docs in function when override did not take doc from the base

Fix goto definition in stubbed modules

---

src/LanguageServer/Impl/Documentation/DocstringConverter.cs
src/LanguageServer/Test/DocstringConverterTests.cs

Fixes #629.
Not the cleanest method; in the future we may need to handle ReST headings better based on the spec, but this covers everything I've seen so far.

Handle more heading cases in docstring converter

---

src/Analysis/Ast/Impl/Analyzer/Symbols/FunctionEvaluator.cs
src/Analysis/Ast/Impl/Extensions/MemberExtensions.cs
src/Analysis/Ast/Impl/Extensions/PythonTypeExtensions.cs
src/Analysis/Ast/Impl/Types/Definitions/IParameterInfo.cs
src/Analysis/Ast/Impl/Types/ParameterInfo.cs
src/Analysis/Ast/Test/FunctionTests.cs

Fixes #604
Treat default value None as nothing since it is not a parameter type but just says the parameter may be missing.

Treat default value None as nothing

---

src/Analysis/Ast/Impl/Analyzer/Handlers/ConditionalHandler.cs

Fixes #668 
- Tooltip is fixed earlier
- Completion was overwritten by `isinstance` handler which redefined `fb` incorrectly. The real fix is #682 but it is way more expensive.
So the fix is to leave variable type as it is in both cases of the conditional.

Remove incorrect handling of isninstance

---

src/Analysis/Engine/Impl/Parsing/Parser.cs
src/Analysis/Engine/Test/ParserTests.cs
src/UnitTests/TestData/Grammar/FunctionLocations.py

Makes the EndIndex of a suite statement use the EndIndex of the last statement, rather than use the current token location, which may have advanced further, past some new line chars.
Example: In some scenarios, the EndIndex of a function ended up the same as the StartIndex of the next function.
That was a regression introduced in https://github.com/Microsoft/PTVS/commit/33bf79ebb758f4592f683b44587bd3e096cabae2#diff-90ae8164360db2dc89b75eeace0edd36L3868
This fixes outlining https://github.com/Microsoft/PTVS/issues/4703 and test discovery https://github.com/Microsoft/PTVS/issues/4908

Fix EndIndex in parser

---

src/Analysis/Ast/Impl/Analyzer/Definitions/IProgressReporter.cs
src/Analysis/Ast/Impl/Analyzer/Definitions/IPythonAnalyzer.cs
src/Analysis/Ast/Impl/Analyzer/Handlers/ConditionalHandler.cs
src/Analysis/Ast/Impl/Analyzer/ProgressReporter.cs
src/Analysis/Ast/Impl/Analyzer/PythonAnalyzer.cs
src/Analysis/Ast/Impl/Dependencies/DependencyResolver.cs
src/Analysis/Ast/Impl/Dependencies/IDependencyResolver.cs
src/Analysis/Ast/Impl/Resources.Designer.cs
src/Analysis/Ast/Impl/Resources.resx
src/LanguageServer/Impl/LanguageServer.cs
src/LanguageServer/Impl/Services/ClientApplication.cs

Fixes #688
- Numbers can go up/down. We can nix numbers and just leave the spinner if that is weird.
- Special class that reduces frequency of reporting traffic and auto-disposes the message when there is no activity.

Basic analysis progress reporting

---

src/Analysis/Ast/Impl/Analyzer/ProgressReporter.cs

Running analysis tests after #687 fails because there is no progress reporting service.

Fix nullref during testing

---

src/LanguageServer/Impl/Documentation/DocstringConverter.cs

Fixes #705.
This isn't the end of the completion speedups, see #704. The regexes should be removed in favor of a real parser, eventually.
Also, I preallocate the builder based on the size of the input, rather than letting it resize needlessly.
I put the regexes as close to their uses as possible, rather than shoving them all at the top or bottom.

Compile docstring converter regexes

---

src/Analysis/Ast/Impl/Modules/PythonModule.cs

Fixes #642.
Reopens #619.
Related #620.
This unfilters `__all__` except for things which are directly from `typing` or are imported modules, though even that may be too strong. The old LS didn't look at `__all__` whatsoever, so maybe all of these should be allowed to come through; you tell me.
Numpy:

Unfilter __all__

---

src/Parsing/Impl/ErrorSink.cs
src/Parsing/Impl/LiteralParser.cs
src/Parsing/Impl/Parser.cs
src/Parsing/Impl/ParserOptions.cs
src/Parsing/Impl/Tokenizer.cs
src/Parsing/Test/ParserTests.cs

We make sure that error reports have correct line numbers and columns, considering the initial location.
This will be useful when we create parsers for f-strings sub expressions

Adding support for setting initial source location in parser

---

src/Analysis/Core/Impl/DependencyResolution/PathResolverSnapshot.Node.cs
src/Analysis/Core/Impl/DependencyResolution/PathResolverSnapshot.cs
src/LanguageServer/Impl/Completion/ImportCompletion.cs
src/LanguageServer/Test/CompletionTests.cs

- Import search now is always happening through PathResolver
- Filtering empty name at the end of module path
- Fixes #716: Language Server 0.2.16 crashes (Request textDocument/completion failed.)
- Fixes #594: Completion support in 'from . import'

Various import completion fixes

---

src/Analysis/Ast/Impl/Analyzer/PythonInterpreter.cs

Fixes #719.
Looking at the stack trace on that issue, `Initialize` occurs, which eventually gets an AST, which then spawns a task which eventually calls `CreateModule`, which refers back to `PythonInterpreter`, whose stub resolver has not yet been instantiated. I don't believe instantiating it earlier has any effect other than that it's there earlier so won't be `null`, as `InitializeAsync` only sets up an internal path resolver.
I'm not really sure if this is the "true" fix, since it seems weird for there to be this sort of cycle, but I'm not the most familiar with this specific bit.

Create stub resolver before builtins

---

src/Analysis/Ast/Impl/Analyzer/PythonAnalyzer.cs
src/Analysis/Ast/Impl/Analyzer/PythonAnalyzerEntry.cs
src/Analysis/Ast/Impl/Dependencies/DependencyGraph.cs
src/Analysis/Ast/Impl/Dependencies/DependencyResolver.cs
src/Analysis/Ast/Impl/Dependencies/DependencyVertex.cs
src/Analysis/Ast/Impl/Dependencies/IDependencyChainWalker.cs
src/Analysis/Ast/Impl/Dependencies/IDependencyResolver.cs
src/Analysis/Ast/Test/DependencyResolverTests.cs
src/Core/Impl/Extensions/TaskExtensions.cs

Stabilization fixes:
- IoC is replaced with direct list of dependencies
- All operations in `ProjectAnalyzerEntry` now happen under individual lock
- Cancellation of analysis can't abort graph change in the middle of the process
- Allow access to AST instance only with corresponding module instance
- Update IPythonModule instance when entry is invalidated

Reduce amount of async code in PythonAnalyzer

---

src/Analysis/Ast/Impl/Analyzer/Handlers/ImportHandler.cs
src/Analysis/Ast/Impl/Analyzer/PythonAnalyzer.cs
src/Analysis/Ast/Impl/Resources.Designer.cs
src/Analysis/Ast/Impl/Resources.resx
src/Analysis/Ast/Impl/scrape_module.py
src/Analysis/Ast/Test/BasicTests.cs
src/Analysis/Ast/Test/ImportTests.cs
src/Analysis/Core/Impl/DependencyResolution/PathResolverSnapshot.cs
src/Analysis/Core/Impl/DependencyResolution/RelativeImportBeyondTopLevel.cs
src/LanguageServer/Test/CompletionTests.cs
src/Parsing/Test/PythonVersions.cs

Also:
- fixed messaging for relative imports that go beyond top-level 
- made amount of tasks in `PythonAnalyzer` dependent on the number of CPU cores

Fix #719: Scraper produces incorrect output for the Anaconda 2X builtin

---

src/Analysis/Ast/Impl/Analyzer/PythonAnalyzer.cs
src/Analysis/Ast/Impl/Analyzer/PythonAnalyzerEntry.cs
src/Analysis/Ast/Impl/Dependencies/DependencyResolver.cs
src/Analysis/Ast/Impl/Modules/CompiledPythonModule.cs
src/Analysis/Ast/Impl/Modules/Definitions/IModuleCache.cs
src/Analysis/Ast/Impl/Modules/ModuleCache.cs
src/Analysis/Ast/Impl/Values/Collections/PythonDictionary.cs
src/Analysis/Ast/Impl/Values/Collections/PythonInstanceIterator.cs
src/Analysis/Ast/Impl/Values/PythonInstance.cs
src/Analysis/Ast/Test/ImportTests.cs
src/Analysis/Ast/Test/ScrapeTests.cs
src/Analysis/Core/Impl/Interpreter/PythonLibraryPath.cs
src/Core/Impl/OS/IProcessServices.cs
src/Core/Impl/OS/ProcessServices.cs

- Reanalyze user module out of the order if required. Helps providing completions earlier (before full initial analysis is completed)
- Skip walker if it is outdated and doesn't have a lot of unanalyzed modules.
- Initialize PriorityProducerConsumer<IDependencyChainNode<TValue>> only when GetNextAsync is called for the first time
- Fix ProcessServices so that error stream doesn't hang the process
- Full Anaconda 2X analysis passes

Stability improvements

---

src/Analysis/Ast/Impl/Analyzer/PythonAnalyzer.cs
src/Analysis/Ast/Impl/Documents/RunningDocumentTable.cs
src/Analysis/Ast/Impl/Modules/PythonModule.cs
src/Analysis/Ast/Test/AnalysisTestBase.cs
src/LanguageServer/Impl/Implementation/Server.cs
src/LanguageServer/Test/CompletionTests.cs
src/LanguageServer/Test/ImportsTests.cs
src/LanguageServer/Test/RdtTests.cs

- IPythonAnalyzer.InvalidateAnalysis is now called when first parse happens
- Fixes for tests that require final analysis while user module (created by RDT.OpenDocument) can have intermediate analysis

Couple of test related fixes

---

src/LanguageServer/Impl/Implementation/Server.cs

Temporary fix until these configurations and the extension are cleaned up together.

Split searchPaths by semicolon to work around extension before config cleanup

---

src/Core/Impl/IO/DirectoryInfoProxy.cs

Fixes #791 .
Creates a FileInfo directly from a file path instead of relying on GetFileSystemInfos.

Simpler creation of FileSystemProxy in EnumerateFileSystemInfos

---

src/LanguageServer/Impl/Implementation/Server.cs

I forgot that `:` appears in `C:\`. I'm going to merge this immediately so we can get a build out with a fix.
Fixes #801.

Remove colon split

---

src/Analysis/Ast/Impl/Modules/Resolution/MainModuleResolution.cs
src/Analysis/Ast/Impl/Modules/Resolution/ModuleResolutionBase.cs
src/Analysis/Ast/Impl/Resources.Designer.cs
src/Analysis/Ast/Impl/Resources.resx

For #809.
If this happens we probably need some better handling, but we should at least print something.
I made it an error, which steals focus as in #810. I can change it to info or similar, but the LS will likely fail to initialize when there is no interpreter (at the moment).

Log when interpreter is not found

---

src/Analysis/Ast/Impl/Modules/CompiledPythonModule.cs
src/Core/Impl/OS/PlatformProcess.cs
src/Core/Impl/OS/ProcessServices.cs

Fixes #817.
This was more complicated than just asking to redirect stderr, as it needs to be read asynchronously to prevent a deadlock while reading both stderr and stdout.

Silence scraper stderr

---

src/Parsing/Impl/Ast/BackQuoteExpression.cs
src/Parsing/Impl/Ast/CallExpression.cs
src/Parsing/Impl/Ast/ErrorExpression.cs
src/Parsing/Impl/Ast/FString.cs
src/Parsing/Impl/Ast/FormatSpecifier.cs
src/Parsing/Impl/Ast/IndexExpression.cs
src/Parsing/Impl/Ast/LambdaExpression.cs
src/Parsing/Impl/Ast/MemberExpression.cs
src/Parsing/Impl/Ast/NameExpression.cs
src/Parsing/Impl/Ast/ParenthesisExpression.cs
src/Parsing/Impl/Ast/SequenceExpression.cs
src/Parsing/Impl/Ast/SliceExpression.cs
src/Parsing/Impl/Ast/StarredExpression.cs
src/Parsing/Impl/Ast/YieldFromExpression.cs
src/Parsing/Test/ParserTests.cs

All nodes have a default NodeName implementation, which is just the type's name.
Nodenames can be used to report syntax errors. (See for example ExpressionWithAnnotation.cs) 
I will use them to report syntax errors related to named expressions.
This PR implements missing nodenames so that errors match what CPython prints.

Changing Expression's nodenames

---

src/LanguageServer/Impl/Indexing/SymbolIndex.cs

Fixes #852.
Not sure why this would be called before an `Add` or similar were to add the doc, but this will at least stop the exceptions from happening.

Work around KeyNotFound exception

---

src/LanguageServer/Impl/Indexing/SymbolIndexWalker.cs
src/LanguageServer/Test/SymbolIndexWalkerTests.cs

Calling AddVarSymbolRecursive on each left side when we walk an AssignmentStatement.
I add handling of ExpressionWithAnnotation and ParenthesisExpression to this method.
Fixes #859 .

Handle complex left side of assignment in SymbolIndexWalker

---

src/Analysis/Ast/Impl/Analyzer/AnalysisModuleKey.cs
src/Analysis/Ast/Impl/Analyzer/PythonAnalyzer.cs
src/Analysis/Ast/Impl/Analyzer/PythonAnalyzerSession.cs
src/Core/Impl/Collections/ImmutableArray.cs
src/Core/Impl/OS/ProcessServices.cs

Leak has been happening because of the async state closure holding references to the dependency graph snapshot walkers even when snapshot wasn't needed.
Code is changed so that all async code is moved into separate session object so that only the last one is referenced by `PythonAnalyzer`. When GC is executed, all non-running sessions will be collected along with their dependency graph snapshot walkers.

Fix #834: Dependency graph memory consumption

---

src/Analysis/Ast/Impl/Analyzer/PythonAnalyzer.cs
src/Analysis/Ast/Impl/Analyzer/PythonAnalyzerSession.cs

Leak has been happening because of the intermediate session has been marked completed, which could trigger a new session while the old one isn't completed. To avoid this, sessions don't reference one another in a form of linked list. Instead, `PythonAnalyzer` holds reference to the currently-running session and updates the reference for the next session if new request comes before current session is completed.

Fix PythonAnalyzerSession leak

---

src/Analysis/Ast/Impl/Analyzer/PythonAnalyzerSession.cs

Closes #851.
Using the same definition of "complete" as the log message. If it did fewer than 100 items, then nothing is sent to prevent spamming for every small change. Open to suggestions for another arbitrary condition instead.
I'd include the system memory, but that'd require a bunch of code to make it work cross platform (or waiting for dotnet/corefx#22660).

Send telemetry event on analysis complete

---

src/LanguageServer/Impl/Formatting/LineFormatter.cs
src/LanguageServer/Test/LineFormatterTests.cs

We treat ':=' the same as normal assignment operator.

LineFormatter: Spaces around ':='

---

src/Analysis/Ast/Impl/Analyzer/PythonAnalyzerSession.cs

I had this condition backwards; the upshot was that nothing would be sent except in a weird case of when a lot of stuff is cancelled at once (which I haven't seen happen), so this code essentially did nothing. Now it'll work as intended.

Fix analysis complete telemetry condition

---

src/Parsing/Impl/ErrorResult.cs
src/Parsing/Test/ErrorAssertions.cs
src/Parsing/Test/ParserTests.cs
src/Parsing/Test/TokenizerTest.cs

Tests that check errors reported by parser were expecting specific index numbers.
Index numbers differ by OS (based on usage of CRLF/LF, etc) so I removed the check fixing the tests for other platforms. Notice that index numbers remain there unused.
This prepares us for a different commit which would delete ErrorInfo and all those numbers from our tests.
I also added tokenizer tests for different newlines.

Remove check for indexes in parser tests

---

src/Analysis/Ast/Impl/Analyzer/Evaluation/ExpressionEval.Collections.cs
src/Analysis/Ast/Impl/Analyzer/Evaluation/ExpressionEval.Operators.cs
src/Analysis/Ast/Impl/Analyzer/ModuleWalker.cs
src/Analysis/Ast/Impl/Types/Collections/PythonCollectionType.cs
src/Analysis/Ast/Impl/Values/Collections/PythonCollection.cs
src/Analysis/Ast/Impl/Values/Collections/PythonDictionary.cs
src/Analysis/Ast/Impl/Values/Definitions/IPythonCollection.cs
src/LanguageServer/Test/ImportsTests.cs

Fixes #881.
This adds `IsExact` to `IPythonCollection`, which is true when `Contents` contains an exact representation of the contents, meaning that the values are set and are known. This boolean is propagated around, and used when looking up `__all__`.
Tensorflow broke because it assigns `__all__` via a comprehension; the comprehension evaluator doesn't actually populate a real collection, instead producing a collection which contains a single member. This could be improved in the future, but by not setting `IsExact` true when that collection is produced, that incomplete value won't be used when looking at `__all__`.

Add IsExact to collection interface, check when deciding to use __all__

---

src/Analysis/Ast/Impl/Analyzer/PythonAnalyzerSession.cs

Because this event is created in the analyzer, I didn't use `Telemetry.CreateEvent`, which would have appended the prefix we need. Hardcode it for now until stuff can move into Core. (I tried moving it into Core but ran into strange build issues.)
Also, send the working set size as well, since *nix platforms don't seem to support paged/peak paged at all. That'll need its own fix that's more complicated.

Fix analysis_complete event name for now, send working MB for *nix platforms

---

src/Analysis/Ast/Impl/Analyzer/ModuleWalker.cs

Search the global scope to ignore builtins, guard against a scope not containing `__all__`.

Fix bad __all__ lookup

---

src/LanguageServer/Impl/Formatting/LineFormatter.cs
src/LanguageServer/Test/LineFormatterTests.cs

Fixes #904.
In the future, we'll probably want to actually format inside fstrings, but because of our implementation the first tokenizer pass doesn't give enough information (but we can expose fstring splitting details elsewhere). I'll open a separate issue for that.

Fix fstrings in line formatter

---

src/Analysis/Ast/Impl/Analyzer/Evaluation/ExpressionEval.Collections.cs

Fixes #877.
Limit the size of exact collections to 1000 items (when they are created from the expressions). This is set high in order to not affect potentially large `__all__` definitions.
probablepeople has a dictionary with more than 150,000 key/value pairs, which takes a very long time to process; 1000 doesn't take very long.

Limit size of exact collections

---

src/Analysis/Ast/Impl/Analyzer/Evaluation/ExpressionEval.Callables.cs

Found in #923.
Is there an easy way to test this, or is this alright as-is?

Open class scope when getting value from ctor

---

src/Analysis/Ast/Impl/Modules/Resolution/MainModuleResolution.cs

To be sure that renames can't happen on things that come from `extraPaths` or `PYTHONPATH` when files are outside the workspace. This isn't a perfect solution due to symlinks, I believe, but this is better than nothing.
`ILookup` accesses return empty iterators, hence the lack of error checking when doing `[true]` and `[false]`.
`Root` is `null` checked because the MRO test manages to create an analyzer without it set.

Treat configuration search paths not under the root as library code

---

src/Analysis/Ast/Impl/Analyzer/Symbols/ModuleSymbolTable.cs

For #875.
The table seems to only be used in the same thread. I found that most of the time analyzing PyQt5 (which has some 30k+ things to process after we scrape it) is inside the concurrent types themselves. Switch them to unlocked types.
It's a bit difficult to verify that this is safe (in lieu of a race detector), so I hacked something in to check accesses to these members to record the thread IDs, which shows only a single thread touching them:
This may not be the end-all-be-all when it comes to PyQt, but this helps significantly. With:
```python
from PyQt5 import QtCore
QtCore.QProcess()
```
Before:
```
Analysis version 358 of 270 entries has been completed in 170094.9184 ms.
```
After:
```
Analysis version 358 of 269 entries has been completed in 10890.3092 ms.
```

Use normal Dictionary/HashSet instead of concurent versions for ModuleSymbolTable

---

src/LanguageServer/Impl/Implementation/Server.cs
src/LanguageServer/Impl/Program.cs

Fixes #849.
This does some preprocessing of searchPaths, removing redundant entries and rooting relative paths.

Preprocess search paths

---

src/LanguageServer/Impl/Implementation/Server.cs
src/LanguageServer/Impl/Indexing/IndexManager.cs

Fixes #977.
This is a weird case, but did work before my search path cleanups. Revert to the old behavior when the root is set to `null`.
To test, open VS Code and close any folders, make a new file and switch its language mode to Python.

Allow root to be null

---

src/Analysis/Ast/Impl/scrape_module.py

Fixes #740.
If `__default__` is set on  a `fused_cython_function`, then trying to access `__kwdefaults__` will segfault (in cython <0.29.6). Check for this condition before using the `inspect` library to look at the function.
This will make it such that the functions like this will have an empty signature, which is wrong, but it's better than crashing entirely and triggering coredump collection/popups.
I'm looking for a way to inspect these functions and find the cython version; so far no luck. If I can find it, then I can make this conditional and on updated libraries not do this check. The shared libraries produced by cython contain the version number, but I'm not sure I want to try reading out the compiled files directly to look for it.
PRs to update affected libraries are ongoing.

Skip bad fused cython functions during scrape

---

src/LanguageServer/Impl/Implementation/Server.cs
src/LanguageServer/Impl/Sources/ReferenceSource.cs
src/LanguageServer/Test/IndexManagerTests.cs

Fixes #1001.
Check for `null` root before looking for files with references, and use the existing URI instead of attempting to make one so that untitled files without a path will work.
This also deletes a test from the indexer; the fix for #977 made it invalid (as `root` is allowed to be null).

Fix nullref when renaming in an untitled file or without a workspace root

---

src/Analysis/Ast/Impl/Analyzer/Evaluation/ExpressionEval.Operators.cs
src/Analysis/Ast/Impl/Types/Collections/PythonCollectionType.cs
src/Analysis/Ast/Impl/Values/PythonInstance.cs
src/Analysis/Ast/Test/ExpressionsTests.cs
src/Analysis/Ast/Test/OperatorTests.cs
src/Parsing/Impl/Ast/PythonOperator.cs

Fixes #860.
This should cover the bulk of the operators; some cases which aren't parsed as BinaryExpressions are not yet handled (e.g. `pow()` should call `__pow__`). Builtins are done by hand, as conversions mean that we can't trust their operator methods. I wrote a script to help me write that code; I'll throw it somewhere when I get the chance.
As far as I've measured, there doesn't seem to be any major performance impact when expanding the operators.

Call methods for binary operators, better handle builtin type conversions

---

README.md

I fixed it in one place, but not the other.

Fix config typo in readme

---

src/Analysis/Ast/Impl/Types/Collections/PythonCollectionType.cs
src/Analysis/Ast/Impl/Types/Collections/PythonDictionaryType.cs

Fixes #1046.
Tests pass as before. There does not appear to be any performance impact, memory usage for my tensorflow test is ~400MB.
I did some checking on what `memberName`s are used with `Call`; while analyzing tensorflow only operators happen, there are no instances where `Call` is used as a constructor.

Defer calls to collections to builtin versions

---

src/Analysis/Ast/Impl/Types/PythonFunctionType.cs

The previous PR didn't also update `Documentation`.

Check _overload when getting docs

---

src/Analysis/Ast/Impl/Dependencies/DependencyVertex.cs
src/Analysis/Ast/Impl/Types/PythonFunctionType.cs

Also use ImmutableArray instead of pair of fields in `PythonFunctionType`.

Fix 1049: Opening second file with PyQt5 import reanalyzes more than it should

---

src/Analysis/Ast/Impl/Documents/DocumentBuffer.cs
src/Analysis/Ast/Impl/Documents/DocumentChange.cs
src/Analysis/Ast/Test/DocumentBufferTests.cs
src/LanguageServer/Impl/Implementation/Server.Documents.cs

Fixes #1058.
The loop in DocumentBuffer could be improved to skip over changes until the last change with `ReplaceAllText` set, but since the function takes an enumerable I'd need to collect it. I think this case is rare, though.

Allow document change event range to be empty

---

src/Analysis/Ast/Impl/Analyzer/DocumentAnalysis.cs
src/Analysis/Ast/Impl/Analyzer/Handlers/FromImportHandler.cs
src/Analysis/Ast/Impl/Analyzer/ModuleWalker.cs
src/Analysis/Ast/Impl/Analyzer/PythonAnalyzerSession.cs
src/Analysis/Ast/Impl/Definitions/IDocumentAnalysis.cs
src/Analysis/Ast/Impl/Modules/PythonModule.cs
src/LanguageServer/Test/ImportsTests.cs

Fixes #867.
I had to change the DocumentAnalysis interface to swap out the ImmutableArray for something that's nullable, to distinguish when `__all__` isn't specified or is unusable. #867 mentions exposing this list through the module; I just accessed it directly through Analysis (since it was there), but I can move it out into its own function/property of the module if that feels better.
Needs a bit more testing, but as far as I can tell, numpy/tensorflow/django (major users of `__all__`) appear to be unaffected by this.

Only use __all__ in star imports

---

src/LanguageServer/Impl/LanguageServer.cs
src/LanguageServer/Impl/Services/TelemetryService.cs
src/LanguageServer/Impl/Telemetry/RequestTimer.cs
src/LanguageServer/Impl/Telemetry/Telemetry.cs

Closes #1068.
I did this in `LanguageServer.cs` instead of further downstream in order to get the "true" request time, i.e. I want to see the time that was spent waiting in the prioritizer if any. Where required, some functions now await their result instead of returning the task, otherwise the timing will only capture the time to create a task and not to complete it.
To limit the number of events sent, it'll only send up to 10 per method. Another solution might be to debounce it using a few IdleTimeActions that reset a boolean per event.
I only added this to the methods I thought would be interesting to examine. Some were explicitly skipped (document changes, line formatting, etc). The `Timer` supports adding extra measures and properties, which are used to send the number of completion …

Add telemetry event and timer for RPC requests

---

src/Analysis/Ast/Impl/Analyzer/Evaluation/ExpressionEval.Hints.cs
src/Analysis/Ast/Test/PepHintTests.cs

Fixes #1073 
Internally expression is extracted and parsed as annotation but since parser was created off the current configuration, in case of 2.7 it was unable to parse type annotations. The fix is to always parse hints as 3.x.

Fix hint extraction in Python 2

---

src/Analysis/Ast/Impl/Inspection/IPythonInspector.cs
src/Analysis/Ast/Impl/Microsoft.Python.Analysis.csproj
src/Analysis/Ast/Impl/inspector.py
src/LanguageServer/Impl/Services/PythonInspectorService.cs
src/LanguageServer/Test/PythonInspectorServiceTests.cs

Opening to get some feedback and thoughts.
The inspector is a partial JSON-RPC server, which takes requests from the LS. Adding more methods is pretty simple, just decorate a function.
~Right now, all it does is get the module member names and `__all__`. This is marginally useful (especially since it's not used anywhere), but we can add more methods to do something like the scraper for full type info, or check for installed versions, etc.~
Some things I'm not sure about are:
- If the process dies, it will be restarted, but the requests that were issued to the crashed process will fail and throw.
- The process should periodically be killed to save on memory.
- The scraper takes extra arguments for path modification which I'm not sure I can really handle due to the process persisting (see …

Python inspector service

---

src/LanguageServer/Impl/Definitions/IDocumentationSource.cs
src/LanguageServer/Impl/Sources/MarkdownDocumentationSource.cs
src/LanguageServer/Impl/Sources/PlainTextDocumentationSource.cs
src/LanguageServer/Impl/Sources/SignatureSource.cs
src/LanguageServer/Test/SignatureTests.cs

Fixes #983.
See also #982 (will need to do the same `name` passthrough for completion and hover).
When the lookup happened and the call target evaluated to a class type, the help would return early, since a class type is not a function type. Now, if it's a class type, then `__init__` is fetched instead.
Also, take the chance to pass down the "real" name of the call to the tooltip.

Handle calls on classes for signature help

---

src/Analysis/Ast/Impl/Modules/PythonModule.cs
src/Analysis/Ast/Impl/Types/PythonClassType.cs
src/Analysis/Ast/Impl/Types/PythonFunctionType.cs
src/Analysis/Ast/Test/ClassesTests.cs
src/Core/Impl/Extensions/IOExtensions.cs

Fixes #1100 
Also harden writing of scraped content as it may occasionally collide scraping same file (I've seen exceptions thrown inside CLR on writing to a closed file.

Prevent SO on documentation fetch

---

src/Analysis/Ast/Impl/Types/Definitions/IParameterInfo.cs
src/Analysis/Ast/Impl/Types/ParameterInfo.cs
src/LanguageServer/Impl/Definitions/IDocumentationSource.cs
src/LanguageServer/Impl/Implementation/Server.cs
src/LanguageServer/Impl/Program.cs
src/LanguageServer/Impl/Protocol/Classes.cs
src/LanguageServer/Impl/Sources/DocumentationSource.cs
src/LanguageServer/Impl/Sources/MarkdownDocumentationSource.cs
src/LanguageServer/Impl/Sources/PlainTextDocumentationSource.cs
src/LanguageServer/Impl/Sources/SignatureSource.cs
src/LanguageServer/Test/FluentAssertions/SignatureInformationAssertions.cs
src/LanguageServer/Test/SignatureTests.cs

Fixes #1038
Fixes #679 
Inactive until extension upgrades to
```json
"vscode-languageclient": "^5.2.1",
"vscode-languageserver": "^5.2.1",
"vscode-languageserver-protocol": "^3.14.1",
```

Update signature parameter handling to LSP 3.14

---

src/gen.py

Closes #724.
The old tests shared an LS/analyzer between everything, but now create one per test module analyzed as one of the test files run is called "types", which triggers #443. Increases overall test time from a couple seconds to 23 seconds (on my machine), but I'd rather not skip tests. Can be changed back later, but 23 seconds isn't too bad.
Will do comparison separately (#1142).

Rewrite gen.py for new LS

---

src/Analysis/Ast/Impl/Modules/BuiltinsPythonModule.cs
src/Analysis/Ast/Impl/Specializations/BuiltinsSpecializations.cs
src/Analysis/Ast/Test/ClassesTests.cs

Specialize getattr()

---

src/Analysis/Ast/Impl/Analyzer/Evaluation/ExpressionEval.Hints.cs
src/Analysis/Ast/Impl/Analyzer/Symbols/FunctionEvaluator.cs
src/Analysis/Ast/Impl/Definitions/AnalysisOptions.cs
src/Analysis/Ast/Impl/Modules/PythonModule.cs
src/Analysis/Ast/Impl/Values/VariableCollection.cs
src/LanguageServer/Impl/Definitions/ServerSettings.cs
src/LanguageServer/Impl/Implementation/Server.cs
src/LanguageServer/Impl/LanguageServer.Configuration.cs
src/LanguageServer/Impl/Sources/DocumentationSource.cs
src/LanguageServer/Test/GoToDefinitionTests.cs
src/Parsing/Impl/Ast/PythonAst.cs

When analysis completes for libraries we no longer need file content. However, we do need to cache some strings for PEP hints to be available if new analysis is requested.
Fixes #1132

Drop file content to conserve memory

---

src/Analysis/Ast/Impl/Extensions/PythonClassExtensions.cs
src/LanguageServer/Impl/Completion/CompletionSource.cs
src/LanguageServer/Impl/Completion/ExpressionCompletion.cs
src/LanguageServer/Test/CompletionTests.cs

Fixes #1154
- Unmangle name when completing on `self` in the class context.
- Hide mangled private members when completing outside of the class on the instance.

Completion presentation for private variables

---

src/Analysis/Ast/Impl/Analyzer/ModuleWalker.cs
src/Analysis/Ast/Impl/Analyzer/Symbols/ClassEvaluator.cs
src/Analysis/Ast/Impl/Modules/PythonModule.cs
src/Analysis/Ast/Test/ImportTests.cs
src/UnitTests/TestData/AstAnalysis/TypingConstants.py
src/UnitTests/TestData/AstAnalysis/TypingConstants.pyi

Fixes #998 
The problem were
- Module member filtering code did not allow export of instances.
- `tkinter` stub prototypes members as `Any` while we actually have better typing from the library (`str`).
Changes
- allow instance export while still restricting re-exporting `typing` members.
- Prefer specific type we discovered in library to `Any`.

Allow exporting of instances from modules and prefer real types to Any

---

src/Analysis/Ast/Impl/Analyzer/Symbols/FunctionEvaluator.cs
src/Analysis/Ast/Impl/Extensions/PythonTypeExtensions.cs
src/Analysis/Ast/Test/FunctionTests.cs
src/LanguageServer/Test/CompletionTests.cs

Fixes #1155
Treat `Any` function return as unknown so we will evaluate it with arguments and figure out proper return type.

Prefer type from parameter annotation to the type of default value

---

src/Analysis/Ast/Impl/Caching/StubCache.cs

Addition to #1147. We should not be checking assembly times anymore since otherwise cache gets invalidated upon install of an update.

Stop checking assembly time in stub cache

---

TROUBLESHOOTING.md
src/Analysis/Ast/Impl/Modules/Resolution/MainModuleResolution.cs

Fixes #989.
Fixes #1013.
Closes #1085.
Closes #1099.
Fixes #1118.
Fixes #1137.
Closes #1169.
Updates #537. (The original use case should have both pth and a config file, but supporting `pth` in general needs to be reexamined.)
Updates #814. (Verify with @karthiknadig that this fixes the vendored dirs in ptvsd.)
Updates #918. (Fixes some issues in that thread, but does not add egg support; could be closed in favor of #196.)
Packages installed as editable show up in the "interpreter paths", as the interpreter's setup has been modified to show that package. Before, when we saw an item in both the interpreter and user search paths lists, the interpreter path won.
Now, if the user search paths explicitly list something, then it will first be removed from the interpreter search path (and …

Fix editable installs when using extraPaths/PYTHONPATH

---

src/Parsing/Impl/Parser.cs
src/Parsing/Impl/Resources.Designer.cs
src/Parsing/Impl/Resources.resx

Moved hard-coded error messages from Parser.cs to Resources.resx. Ran unit tests from 'Microsoft.Pythong.Parsing.Tests.ParserTests', all tests passed except for 'Microsoft.Pythong.Parsing.Tests.ParserTests.Errors.' Noted failed test <a href="https://github.com/microsoft/python-language-server/issues/647#issuecomment-497893526">here</a>. Believe test failure existed prior to my changes, reverted failing code to original state, test still failed.

Move strings in parser to resources issue #647

---

src/Parsing/Impl/LiteralParser.cs
src/Parsing/Impl/Parser.cs

This pull request updated the literal strings in the "throw new ArgumentNullException" to use thrownameof() instead of string literals.

ArgumentNullException to use nameof in Parser project Issue #228

---

src/LanguageServer/Impl/Completion/CompletionSource.cs
src/LanguageServer/Impl/Completion/ErrorExpressionCompletion.cs
src/LanguageServer/Impl/Completion/ExpressionLocator.cs

Suppress completion in non-user code

---

src/Analysis/Ast/Impl/Modules/PythonModule.cs

Fixes #1202.
`LoadContent()` gets the content, but does nothing with it. The other overload is the one with side effects, so call it instead.
There are probably other fixups that could be done in this area (the LibraryAnalysis constructor having side effects and clearing out things it's passed makes things complicated), but this is the minimal change until the double-final-analysis thing is fixed.

Actually populate buffer when reloading Ast

---

src/Analysis/Ast/Impl/Modules/Resolution/MainModuleResolution.cs

Fixes #1175.
Fixes #1209.
Updates #537.
If the workspace root is allowed to be an interpreter path, the analysis hangs. This only happens with editable installs, which modify the interpreter via pth files.

Do not allow workspace root to be an interpreter/library path

---

src/Analysis/Ast/Impl/Analyzer/Evaluation/ExpressionEval.cs

Fixes #1219.
This can happen in some weird layouts. Instead of failing, just take the default location.

Fix arg with null location

---

src/Analysis/Ast/Impl/Modules/PythonModule.cs

Since it is locked in other cases when we are resetting or reloading.

Lock document content 

---

src/LanguageServer/Impl/Completion/CompletionItemSource.cs
src/LanguageServer/Impl/Completion/CompletionSource.cs
src/LanguageServer/Impl/Completion/ExpressionCompletion.cs
src/LanguageServer/Impl/Implementation/Server.cs
src/LanguageServer/Test/CompletionTests.cs

Fix addBrackets setting

---

src/Analysis/Ast/Impl/Values/Scope.cs

Not entirely sure how completions ended up there since they are supposed to be suppressed, but if AST is dropped, scope does can lose its node and then should just use the empty AST.

Handle library analysis better

---

src/Analysis/Ast/Impl/Analyzer/Evaluation/ExpressionEval.Operators.cs
src/Analysis/Ast/Impl/Diagnostics/ErrorCodes.cs
src/Analysis/Ast/Impl/Resources.Designer.cs
src/Analysis/Ast/Impl/Resources.resx
src/Analysis/Ast/Test/LintOperatorTests.cs

I basically hooked into what Jake is doing; we agreed that it is probably best to only give diagnostic error only on the builtin Python types. I structured the error message to be nearly the same as the Python interpreter's runtime error message, but that is subject to change.
For testing, I feel that a lot of the functionality is related to Jake's parsing of binary operations, so I should rely on the tests for that part of the software to prove the correctness of the diagnostic message instead of trying to recreate new tests that may or may not be duplicates of his.

Adding diagnostic error on binary operations with incompatible types

---

src/Analysis/Ast/Impl/Diagnostics/ErrorCodes.cs
src/Analysis/Ast/Impl/Resources.Designer.cs
src/Analysis/Ast/Impl/Resources.resx
src/Analysis/Ast/Impl/Specializations/Typing/TypingModule.cs
src/Analysis/Ast/Test/LintNewTypeTests.cs

For example:
```
from typing import NewType
T = NewType(5, int)
```
Now gives a diagnostic error. 
This PR relies on work done in PR #1259, so it should be merged after that.

When NewType is called and the first argument is not a string, make a diagnostic message

---

src/Analysis/Ast/Impl/Modules/Resolution/MainModuleResolution.cs
src/Analysis/Ast/Impl/get_search_paths.py
src/Analysis/Ast/Test/PathClassificationTests.cs
src/Analysis/Core/Impl/Interpreter/PythonLibraryPath.cs
src/Core/Impl/Extensions/StringExtensions.cs
src/Core/Impl/IO/PathUtils.cs
src/LanguageServer/Impl/Implementation/Server.cs

Fixes #1213.
Fixes #537. (`pth` files will be handled automatically)
This does not change the algorithm overall, just moves it to another place and makes it more consistent (running on all of the paths, and not just a subset). The `get_search_paths.py` script uses the `site` library to identify which of its package paths came from `pth` files. Paths which aren't inside a stdlib path but are likely user code can be automatically classified as such. Note that the ordering of library paths should remain the same; I don't do any sort of depth sorting at the moment, but may need to do so in the future.
As the search path classification was moved, I'm now able to write tests for it, and have done so.
A future PR will make a couple more changes to allow the interpreter paths generated in …

Rework search path resolution

---

src/Analysis/Ast/Impl/Analyzer/Evaluation/ExpressionEval.Generics.cs
src/Analysis/Ast/Impl/Analyzer/Evaluation/ExpressionEval.cs
src/Analysis/Ast/Test/LintGenericTests.cs

This is a fix for the issue I talked about in our meeting. The issue was that when in an index expression, if you do:
```
A = [1,2,3]
A[]
```
We would get an error expression for the inside part, but we would fall into the default case in evaluating it and return Unknown type for the arguments when there are actually no arguments and we should (in my opinion) return null.

No diagnostic message when Generic is called with no args

---

src/Analysis/Ast/Impl/Analyzer/Symbols/ClassEvaluator.cs
src/Analysis/Ast/Impl/Diagnostics/ErrorCodes.cs
src/Analysis/Ast/Impl/Resources.Designer.cs
src/Analysis/Ast/Impl/Resources.resx
src/Analysis/Ast/Impl/Types/PythonClassType.cs
src/Analysis/Ast/Test/InheritNonClassTests.cs

same as inherit-non-class for pylint

When a class inherits from something that is not a class, give a diagnostic error

---

src/Analysis/Ast/Impl/Analyzer/Handlers/FromImportHandler.cs
src/Analysis/Ast/Impl/Analyzer/Handlers/ImportHandler.cs
src/Analysis/Ast/Impl/Analyzer/PythonAnalyzerSession.cs
src/Analysis/Ast/Impl/Modules/Definitions/IModuleManagement.cs
src/Analysis/Ast/Impl/Modules/PythonModule.cs
src/Analysis/Ast/Impl/Modules/Resolution/MainModuleResolution.cs
src/Analysis/Ast/Test/AnalysisTestBase.cs
src/Analysis/Ast/Test/TypeshedTests.cs
src/Analysis/Core/Impl/DependencyResolution/PathResolverSnapshot.cs
src/Analysis/Core/Impl/Interpreter/PythonLibraryPath.cs
src/Core/Impl/Extensions/StringExtensions.cs
src/Core/Impl/IO/PathUtils.cs
src/LanguageServer/Test/CompletionTests.cs
src/LanguageServer/Test/GoToDefinitionTests.cs
src/LanguageServer/Test/ImportsTests.cs
src/UnitTests/Core/Impl/TestData.cs

- Fix #1314: NRE in HandleModuleImportStar bug
- Fix #1318: PathUtils.IsNormalizedPath and PathUtils.NormalizePath work incorrectly with UNC
- Fix #1320: Incorrect relative import handling in Python 2x
- Fix #1321: If one user paths is part of the name of another, PathResolverSnapshot is built incorrectly
- Fix paths in tests
- Remove `IModuleManagement.SetUserSearchPaths`

Bug and test fixes

---

src/Analysis/Ast/Test/PathClassificationTests.cs
src/Analysis/Core/Impl/Interpreter/PythonLibraryPath.cs

Remove temp folder from paths, fix site packages outside of stdlib paths

---

src/Analysis/Ast/Impl/Extensions/MemberExtensions.cs
src/LanguageServer/Impl/Implementation/Server.Editor.cs
src/LanguageServer/Impl/Implementation/Server.cs
src/LanguageServer/Impl/LanguageServer.cs
src/LanguageServer/Impl/Protocol/Classes.cs
src/LanguageServer/Impl/Sources/DefinitionSource.cs
src/LanguageServer/Impl/Sources/ReferenceSource.cs
src/LanguageServer/Test/GoToDefinitionTests.cs

Closes #494
Closes #1138
And change behavior of goto definition to go to the root.

Implement goto declaration

---

src/LanguageServer/Impl/Completion/CompletionSource.cs
src/LanguageServer/Test/CompletionTests.cs

It will give completions for 
```
....
```
So I'm not sure what the intended behavior for that is, but on regular ellipsis it doesn't give completions.

No completions on ellipsis

---

src/Analysis/Ast/Impl/Analyzer/Symbols/ClassEvaluator.cs
src/Analysis/Ast/Test/LintInheritNonClassTests.cs

I think it would be good to have a PR in the future that would add a field to `IPythonFunctionType` that allowed linting to tell if something was specialized as a function for convenience but should be treated as a class. 
Fixes #1377

Allowing classes to inherit from all specialized functions

---

src/Analysis/Ast/Impl/Documents/Definitions/IRunningDocumentTable.cs
src/Analysis/Ast/Impl/Documents/RunningDocumentTable.cs
src/LanguageServer/Impl/Implementation/Server.Telemetry.cs

Fixes #1379.
Can't use `GetDocuments().Count` as it collects the entire list under lock.

Add RDT count to the analysis_complete event

---

src/Analysis/Ast/Impl/Analyzer/Symbols/SymbolCollector.cs
src/Analysis/Ast/Impl/Types/PythonFunctionType.cs
src/Analysis/Ast/Test/ClassesTests.cs

Fixes #1335, for now.
This could stand to be improved by somehow allowing the declaring type to be null, but that is a more complicated fix, and just falling back to a function provides some usability and stops the NREs.

Fallback to function when property's declaringType is unknown

---

src/Analysis/Ast/Impl/Caching/StubCache.cs
src/Analysis/Ast/Impl/scrape_module.py
src/Analysis/Ast/Test/ClassesTests.cs
src/Analysis/Ast/Test/FluentAssertions/MemberAssertions.cs

Closes #1403 
`type name as string` should not be adding `()` since it turns type info into an instance.
Changes version of the stub cache so it gets re-generated on user machine.

Fix 'type name as string' conversion in scraper.

---

src/Analysis/Ast/Impl/Analyzer/Definitions/LookupOptions.cs
src/Analysis/Ast/Impl/Analyzer/Evaluation/ExpressionEval.Scopes.cs
src/Analysis/Ast/Impl/Analyzer/Handlers/AssignmentHandler.cs
src/Analysis/Ast/Impl/Linting/UndefinedVariables/ExpressionWalker.cs
src/Analysis/Ast/Impl/Types/PythonClassType.Generics.cs
src/Analysis/Ast/Impl/Types/PythonClassType.cs
src/Analysis/Ast/Impl/Types/PythonType.cs
src/Analysis/Ast/Impl/Values/Definitions/IVariable.cs
src/Analysis/Ast/Impl/Values/Variable.cs
src/Analysis/Ast/Test/ClassesTests.cs
src/Analysis/Ast/Test/FunctionTests.cs
src/Core/Impl/Text/IndexSpan.cs
src/LanguageServer/Impl/Completion/TopLevelCompletion.cs
src/LanguageServer/Impl/Sources/DefinitionSource.cs
src/LanguageServer/Impl/Sources/HoverSource.cs
src/LanguageServer/Test/CompletionTests.cs
src/LanguageServer/Test/HoverTests.cs

Fixes #1231
Root cause is that class evaluator was declaring members as variables and then collected variables into members. Smaller change than earlier.
- Add `IsClassMember` to variable. `VariableSource` does not fit since `class member` behaves like a flag.
- Add option to scope search to return class member variables.
- In linter and hover use option to obtain all variables. In completions use regular option.

Special handling of variables representing class members

---

src/Analysis/Ast/Impl/Analyzer/Handlers/AssignmentHandler.cs
src/Analysis/Ast/Test/AssignmentTests.cs
src/Analysis/Ast/Test/LintInheritNonClassTests.cs

Ignoring assignment statements that occur before class and function declaration

---

src/Analysis/Ast/Impl/Analyzer/Evaluation/ExpressionEval.Scopes.cs
src/Analysis/Ast/Impl/Analyzer/Handlers/AssignmentHandler.cs
src/Analysis/Ast/Impl/Analyzer/Handlers/FromImportHandler.cs
src/Analysis/Ast/Test/ImportTests.cs

Fixes #1257.
Cherry picked out of #1429.

Fix import * over local declarations

---

src/Analysis/Ast/Impl/Analyzer/PythonAnalyzerSession.cs

For #1401.
We should really have more info here than just the message, but I'm also worried that this might be _too_ much for long stack traces. Thoughts?

Log full exception on session failure

---

src/Analysis/Ast/Impl/Analyzer/Symbols/ClassEvaluator.cs
src/Analysis/Ast/Test/LintInheritNonClassTests.cs

Before it would have double messages on the function which can be pretty annoying.

Moving location of inherit-non-class diagnostic to arguments

---

src/Analysis/Ast/Impl/Analyzer/Evaluation/ExpressionEval.Annotations.cs
src/Analysis/Ast/Impl/Analyzer/Evaluation/ExpressionEval.Generics.cs
src/Analysis/Ast/Impl/Types/PythonFunctionOverload.cs
src/Analysis/Ast/Impl/Utilities/AstUtilities.cs
src/Analysis/Ast/Test/GenericsTests.cs
src/Analysis/Ast/Test/TypeshedTests.cs
src/LanguageServer/Test/SignatureTests.cs

Fixes #1186.
Handles cases such as:
```
class A: ...
class Bar: ...
def tmp(v: 'List[str]') -> 'List[str]'
def tmp(v: 'Bar') -> List['Bar']
def tmp(v: 'str') -> 'A'
```
So instead of returning unknown, we try to evaluate what is inside the quotes.
* Updated the type annotation hint code to handle forward references so parameters get the correct types.
* Handled values in quotes when creating Generic types
* Handled forward reference return value hints

String forward reference support

---

src/Analysis/Ast/Impl/Analyzer/Evaluation/ExpressionEval.Scopes.cs
src/Analysis/Ast/Impl/Analyzer/Handlers/AssignmentHandler.cs
src/Analysis/Ast/Impl/Analyzer/PythonAnalyzerSession.cs
src/Analysis/Ast/Impl/Analyzer/Symbols/ClassEvaluator.cs
src/Analysis/Ast/Impl/Extensions/EvaluatorExtensions.cs
src/Analysis/Ast/Impl/Extensions/MemberExtensions.cs
src/Analysis/Ast/Impl/Extensions/ScopeExtensions.cs
src/Analysis/Ast/Impl/Types/PythonClassType.Generics.cs
src/Analysis/Ast/Impl/Types/PythonClassType.cs
src/Analysis/Ast/Impl/Values/Definitions/IScope.cs
src/Analysis/Ast/Impl/Values/EmptyGlobalScope.cs
src/Analysis/Ast/Impl/Values/Scope.cs
src/Analysis/Ast/Test/ClassesTests.cs
src/Analysis/Ast/Test/LibraryTests.cs
src/Analysis/Ast/Test/LintNewTypeTests.cs
src/UnitTests/TestData/AstAnalysis/Base.py

Fixes #1495 
- Since we don't handle reassignments, improve handling of imported bases like 
```python
from Base import A, B
class A(A, B):
def methodA(self, x):
return x
class C(B): ...
class B(A):
def methodB(self, x):
return x
```
by declaring imported variables in regular collection as well as in special `imported` collection so they can be found when we need to resolve class base.
- Decide on declaration or import depending on location
- Implement deep filtering of circular base chains
- Tests

Improve handling of circular and imported class bases

---

src/LanguageServer/Impl/LanguageServer.Lifetime.cs
src/LanguageServer/Impl/Protocol/Classes.cs

Check for workspace/configuration availability before sending request

---

src/LanguageServer/Impl/LanguageServer.cs

Fixes #1507.
The measures are just for performance metrics. If `null` is getting returned, then we should have zeros, not crash.

Fix a few NREs with request measures

---

src/Core/Impl/IO/DirectoryInfoProxy.cs
src/Core/Test/AssemblySetup.cs
src/Core/Test/DirectoryInfoProxyTests.cs

Fixes #1512.
Since we're constructing `FileInfo` ourselves, and the matcher returns things relative to the directory the matching started at, ensure that we combine things to not not return a relative FileInfo.
Needs some testing to ensure that the proxy interface returns something consistent.

Ensure FileInfo is not relative in DirectoryInfoProxy

---

src/Analysis/Ast/Test/FluentAssertions/AssertionsUtilities.cs

In #1526 my find and replace matched the variables and not just the types. Fix that.

Fix bad find and replace in AssertionsUtilities

---

src/Analysis/Ast/Impl/Documents/DocumentBuffer.cs
src/Analysis/Ast/Test/DocumentBufferTests.cs
src/LanguageServer/Impl/Implementation/Server.Documents.cs
src/LanguageServer/Impl/LanguageServer.cs
src/LanguageServer/Impl/Protocol/Messages.cs

Fixes #1543 
- Changes were applied incorrectly. Changes across line spans caused buffer corruption. Typical example is undoing multiple changes via fast `Ctrl+Z`.
- Simplified change handling: per LSP, any sequence applies
```
* The actual content changes. The content changes describe single state changes
* to the document. So if there are two content changes c1 and c2 for a document
* in state S then c1 move the document to S' and c2 to S''.
```
and we can now handle this since line splits update after each change.
- Implement new line location without creating extra strings
- Add tests for new lines as well as for multi-line edits.
- Remove unused flags
- Remove change reordering/versions.

Implement proper line split + tests

---

src/Core/Impl/Text/StringSpan.cs
src/Parsing/Impl/FStringParser.cs
src/Parsing/Test/ParserTests.cs
src/UnitTests/TestData/Grammar/FStringEquals.py
src/UnitTests/TestData/Grammar/FStringEqualsErrors.py

Fixes #1102.
Plus a few extra cleanups (methods to properties, error reporting fixes, etc)

Add support for Python 3.8 fstring debug `=`

---

src/LanguageServer/Impl/Indexing/SymbolIndexWalker.cs
src/LanguageServer/Test/SymbolIndexWalkerTests.cs

Fixes #958.
Took the opportunity to modify `Root` to make it obvious that it should not be modified.
Note that in the case where a symbol with no name has children, it's going to still be skipped; in order to do otherwise we'd need to pick a name for it (which is possible to do if we find that it's necessary).

Ignore null/empty named symbols during symbol index walk

---

src/Analysis/Ast/Test/AssignmentTests.cs
src/Analysis/Ast/Test/LintUndefinedVarsTests.cs
src/LanguageServer/Test/HoverTests.cs

Encountered this while I was working on the scope stuff. I think for version specific stuff like the := operator, we should specify the version of the test.

Fix Python 3.8 version checks in tests

---

src/Parsing/Impl/Tokens/Tokenizer.cs

PTVS needs to initialize the Tokenizer with an existing state, but that property was removed in January, probably because that looked unused in the language server code base.

Add back the State property getter to the Tokenizer.

---

src/Core/Impl/Extensions/TaskCompletionSourceExtensions.cs
src/Core/Impl/Threading/PriorityProducerConsumer.cs
src/Core/Test/PriorityProducerConsumerTest.cs
src/LanguageServer/Impl/LanguageServer.cs
src/LanguageServer/Impl/Program.cs

simple clean up. PriorityProducerConsumer was using List but removed element from head. but never took advantage of indexer so changed it to use LinkedList.

use LinkedList instead of List in PriorityProducerConsumer

---

src/Analysis/Ast/Impl/Analyzer/Handlers/FromImportHandler.cs

https://github.com/microsoft/python-language-server/pull/1565 missed case when imported item is a variable and it has to be variable and not a value so references can be added to it.

Fix find references regression

---

src/LanguageServer/Impl/Completion/TopLevelCompletion.cs
src/Parsing/Impl/PythonKeywords.cs

It didn't seem appropriate to leave it in the current namespace/location since everything in there was private. I can move it somewhere else if you don't like it in parser project.

Make PythonKeywords class public for use in PTVS

---

src/Analysis/Ast/Impl/Analyzer/AnalysisWalker.cs
src/Analysis/Ast/Impl/Analyzer/Evaluation/ExpressionEval.Callables.cs
src/Analysis/Ast/Impl/Analyzer/Handlers/FromImportHandler.cs
src/Analysis/Ast/Impl/Types/LocatedMember.cs
src/Analysis/Ast/Impl/Types/PythonType.cs
src/Analysis/Ast/Test/ReferencesTests.cs
src/Parsing/Impl/Ast/CallExpression.cs

Process function call arguments so they get references added

---

src/Analysis/Ast/Impl/Analyzer/Evaluation/ExpressionEval.Annotations.cs
src/Analysis/Ast/Impl/Analyzer/Evaluation/ExpressionEval.Callables.cs
src/Analysis/Ast/Impl/Analyzer/Evaluation/ExpressionEval.Collections.cs
src/Analysis/Ast/Impl/Analyzer/Evaluation/ExpressionEval.Generics.cs
src/Analysis/Ast/Impl/Analyzer/Evaluation/ExpressionEval.Operators.cs
src/Analysis/Ast/Impl/Analyzer/Evaluation/ExpressionEval.cs
src/Analysis/Ast/Impl/Analyzer/Evaluation/FunctionCallEvaluator.cs
src/Analysis/Ast/Impl/Analyzer/Handlers/AssignmentHandler.cs
src/Analysis/Ast/Impl/Analyzer/Symbols/ClassEvaluator.cs
src/Analysis/Ast/Impl/Analyzer/Symbols/FunctionEvaluator.cs
src/Analysis/Ast/Impl/Types/ArgumentSet.cs
src/Analysis/Ast/Test/ClassesTests.cs

Fixes #1600 
We must make sure lookup options for name resolution are passed since additional `ClassMembers` is passed in the class scope context so we can find class members without `self.`.

Make sure we pass lookup options to expression evaluation

---

src/Analysis/Ast/Test/AnalysisTestBase.cs

Try and cancel analysis requests if the tests appear to be hanging. Doesn't fix the underlying issue, but helps us work on other things.

Add 1 minute timeout to analysis tests run via AnalysisTestBase

---

src/Analysis/Ast/Impl/Analyzer/PythonInterpreter.cs
src/Analysis/Ast/Impl/Values/PythonNone.cs
src/Analysis/Ast/Test/LintInheritNonClassTests.cs
src/Analysis/Ast/Test/TypingTests.cs

Fixes #1624.
None is its own type and instance. Added a test for the typing behavior (None being an acceptable type), as well as some tests for inheriting from None to verify that it still lints as wrong.

Treat None as its own type and instance

---

src/Analysis/Ast/Impl/Analyzer/AnalysisModuleKey.cs
src/Analysis/Ast/Impl/Dependencies/DependencyCollector.cs
src/Analysis/Ast/Impl/Documents/RunningDocumentTable.cs
src/Analysis/Ast/Impl/Modules/BuiltinsPythonModule.cs
src/Analysis/Ast/Impl/Modules/CompiledBuiltinPythonModule.cs
src/Analysis/Ast/Impl/Modules/CompiledPythonModule.cs
src/Analysis/Ast/Impl/Modules/Definitions/ModuleCreationOptions.cs
src/Analysis/Ast/Impl/Modules/PythonModule.cs
src/Analysis/Ast/Impl/Modules/PythonVariableModule.cs
src/Analysis/Ast/Impl/Modules/Resolution/MainModuleResolution.cs
src/Analysis/Ast/Impl/Modules/Resolution/ModuleResolutionBase.cs
src/Analysis/Ast/Impl/Modules/SpecializedModule.cs
src/Analysis/Ast/Impl/Modules/StubPythonModule.cs
src/Analysis/Ast/Impl/Types/Definitions/IPythonModule.cs

- Fix analysis module key duplication is stubs: IsTypeshed is set in `StubPythonModule` after base initiated loading of content and analysis so occasionally there may be two keys in the analyzer - one with IsTypeshed set and one without.
- Fix builtins module resolution in typeshed - so it resolves to the same common builtins and not to stub

Fix analysis module key duplication is stubs

---

src/Analysis/Ast/Impl/Analyzer/Handlers/AssignmentHandler.cs
src/Analysis/Ast/Impl/Analyzer/Handlers/SequenceExpressionHandler.cs
src/Analysis/Ast/Impl/Utilities/ValueEnumerator.cs
src/Analysis/Ast/Test/TypingTests.cs

Fixes #1622.
If we're trying to unpack a union, store a ValueEnumerator per union item, then produce unions as items from each of the nested enumerators.
Note that since the unions are of types and are not values, we need to do some extra work to shift back and forth between types and instances where needed.
Also:
- Replace the `Next` property with a method, since it has side effects.
- Replace a comment I added in a previous PR with a new one explaining what's _actually_ happening.
- Use ImmutableArray in ValueEnumerator (the default works better).

Handle Unions of collections in ValueEnumerator, recursively

---

src/LanguageServer/Impl/LanguageServer.Configuration.cs

So we can have "Default" in the extension and be able to pick.

Use a real default option for caching, set default back to None temporarily

---

src/Analysis/Ast/Test/FunctionTests.cs
src/Parsing/Impl/Ast/TypeAnnotation.cs

Fixes #1640.
This is sort of a red herring, since the exception will actually be caught then the entire annotation converted to `default`, but explicitly pushing something onto the op stack when an unknown constant value is seen is better than destroying the entire annotation parse.

Avoid breaking the op stack when an unknown constant value is found

---

src/Analysis/Ast/Test/AnalysisTestBase.cs

With the old timeout, sessions over a minute would fall apart as things would start getting cancelled.

Use an infinite timeout when debugger is attached

---

src/Analysis/Ast/Impl/Documents/DocumentBuffer.cs

User may try and edit library file where we have already dropped the content.
Fixes #1651

Remove invalid operation

---

src/Analysis/Ast/Impl/get_search_paths.py
src/Analysis/Core/Impl/Interpreter/PythonLibraryPath.cs

Fixes #1676.
Make `get_search_paths.py` remove subpaths of its own directory from the returned paths.
Only question I would have is if `clean` should also be doing `os.path.realpath` to resolve symlinks (i.e. what if the language server's directory is symlinked somewhere up the chain).

Remove get_search_path.py's path from the search paths it returns

---

src/Parsing/Impl/Parser.cs
src/Parsing/Test/ParserTests.cs
src/UnitTests/TestData/Grammar/ForFinallyContinue.py

Fixes #1688.
Missed this during my initial reading of the 3.8 changes.

Allow continue in finally block in 3.8+

---

src/Analysis/Ast/Impl/Caching/StubCache.cs
src/Analysis/Ast/Impl/scrape_module.py
src/LanguageServer/Impl/Completion/CompletionItemSource.cs
src/LanguageServer/Impl/Definitions/IDocumentationSource.cs
src/LanguageServer/Impl/Sources/DocumentationSource.cs
src/LanguageServer/Impl/Sources/HoverSource.cs
src/LanguageServer/Impl/Sources/MarkdownDocumentationSource.cs
src/LanguageServer/Impl/Sources/PlainTextDocumentationSource.cs
src/LanguageServer/Test/CompletionTests.cs
src/LanguageServer/Test/HoverTests.cs

Fixes #1173.
Fixes #1701.
Adds class `__init__` parameters to the completion documentation, if possible. Also, fixes the scraper to not output the wrong `__init__` function signature for `object`. And, remove the `class` keyword prefix, as it's inconsistent with hovers and other completions and ends up breaking syntax highlighting.
No DB version bump needed for the scraper change, as we do not store the builtins module which contains `object`.

Add __init__ parameters to class completion documentation

---

src/Analysis/Ast/Impl/Caching/Definitions/IModuleDatabaseService.cs
src/Caching/Impl/ModuleDatabase.cs

For #1601.
These locks effectively do nothing.
- `ModuleExistsInStorage` would still be affected by the ordering of DB creation and checking regardless of the lock. Realistically, the file system is preventing internal race conditions, so we don't have to.
- `StoreModuleAnalysis` creates the LiteDB instances, but LiteDB has internal file locking mechanisms, so we don't need to repeat that here either.
`_lock` protects the dependency dictionary (as it's not a concurrent one), so can't just be removed.

Do not lock module database when working with database files

---

src/LanguageServer/Impl/Completion/ImportCompletion.cs
src/LanguageServer/Test/CompletionTests.cs

Fixes #1647.
The completion context was correct (ImportStatement), however we were offering non-module members, which are only valid when using `from something import ...`, and not `import ...`. Filter them out.
Now:

Do not show non-module members as completion candidates in regular import statement

---

src/UnitTests/Core/Impl/MarkupUtils.cs
src/UnitTests/Core/Impl/UnitTests.Core.csproj

this helper let one to annotate test text itself to mark locations.
see "add import" PR for example.
splitting this part from "add import" PR so that I can use it in "unused import" PR.
ex)
https://github.com/microsoft/python-language-server/pull/1656/files#diff-185d2e737eec3d6cf9c9812e2fc64bc3R50
https://github.com/microsoft/python-language-server/pull/1656/files#diff-8930788336d0cecf1c97200811f09869R115

add unit test markup utilities

---

src/Analysis/Ast/Impl/Analyzer/PythonAnalyzer.cs
src/Analysis/Ast/Impl/Analyzer/PythonAnalyzerSession.cs
src/Analysis/Ast/Impl/Caching/CacheFolders.cs
src/Analysis/Ast/Impl/Caching/CacheService.cs
src/Analysis/Ast/Impl/Microsoft.Python.Analysis.csproj
src/Analysis/Ast/Impl/Resources.Designer.cs
src/Analysis/Ast/Impl/Resources.resx
src/Analysis/Ast/Test/AnalysisTestBase.cs
src/Analysis/Core/Impl/Microsoft.Python.Analysis.Core.csproj
src/Caching/Impl/Microsoft.Python.Analysis.Caching.csproj
src/Core/Impl/Extensions/StringExtensions.cs
src/Core/Impl/Microsoft.Python.Core.csproj
src/LanguageServer/Impl/Implementation/Server.cs
src/LanguageServer/Impl/LanguageServer.Lifetime.cs
src/LanguageServer/Impl/LanguageServer.cs
src/LanguageServer/Impl/Microsoft.Python.LanguageServer.csproj
src/LanguageServer/Impl/Optimization/IProfileOptimizationService.cs
src/LanguageServer/Impl/Optimization/ProfileOptimizationService.cs
src/LanguageServer/Impl/Program.cs
src/Parsing/Impl/Microsoft.Python.Parsing.csproj

and take advantage of ProfileOptimization (https://docs.microsoft.com/en-us/dotnet/api/system.runtime.profileoptimization?view=netcore-3.0) to make starting time faster 
some experiment user did on the web - https://www.dotnetperls.com/profileoptimization
...
confirmed that background JIT (multicore jit) and tiered compilation are enabled using perfview with background jit option
and confirmed things like parsing, analysis code is concurrently jitted from BG.
also, as vscode is used longer, I see more tiered compilation happens.
for now, I added profile optimization only on startup code path, but it is not actually limited to start-up scenario, one can put it any place where we want concurrent jit with different profile name such as "find all references" or "rename" and etc if there are …

enable tiered compilation and use latest C# lang version

---

src/Caching/Impl/ModuleDatabase.cs

#1686 was significant enough that old DB versions don't work right anymore. Bump this to reset everything.

Bump database version

---

src/LanguageServer/Impl/LanguageServer.Configuration.cs

After #1686, caching is poorly behaved. Disable it by default for now.

Set default caching level to None

---

src/Analysis/Ast/Impl/Analyzer/Symbols/FunctionEvaluator.cs
src/Analysis/Ast/Test/LintNoMethodArgumentTests.cs

Fixes #1695 
Figured I should clean that up.
When there is an error in parameters, `FunctionDefinition.Body` will be null, parameters field is never null.

Don't lint "no-method-argument" until user types (

---

src/LanguageServer/Impl/LanguageServer.cs

Since this is a longer call, send an event for it with the count.

Track codeAction RPC time and count

---

src/LanguageServer/Impl/LanguageServer.Configuration.cs
src/LanguageServer/Impl/LanguageServer.Lifetime.cs
src/LanguageServer/Impl/LanguageServer.cs

For #1697.
Try adding a new priority level for the second step of the init process. Also, debug assert that the initialization has happened before any other requests so we can try and catch it during normal use.
Also, use an enum for the priority levels to make priority changes a little less weird.
I think there might be an issue in the prioritizer where two requests of the same priority come in, one gets handled correctly, but the other gets handed off to another queue. Not entirely certain, but adding an extra level may work around it (and we can see if this helps).

Add "initialized" priority level for two-step init process, debug-assert initialized in handlers

---

src/LanguageServer/Impl/LanguageServer.Configuration.cs

For #1758.
Since caching does not currently work at _any_ level, disable it regardless of the user setting for now until it's working properly to prevent looping on users who have changed the setting.
This should be reverted in #1757.

Disable caching regardless of user level

---

src/Analysis/Ast/Impl/Analyzer/Evaluation/FunctionCallEvaluator.cs

Fixes #1768.
The body may be null (not present), so cannot have `Walk` called on it. Matches other instances of `Body?.Walk` in other parts of the code.

Do not attempt to walk null body in EvaluateCall

---

src/LanguageServer/Impl/Implementation/Server.cs

Do not allow the analyzer to be reset if the server is still initializing

---

src/Analysis/Ast/Impl/Modules/PythonModule.cs

Debugging for #1776.
Doesn't fix the core issue that we're spawning tasks we can't keep track of, but helps trying to find the crashes.

Log parse exceptions instead of just throwing them away

---

src/Analysis/Ast/Impl/Microsoft.Python.Analysis.csproj
src/Analysis/Ast/Test/Microsoft.Python.Analysis.Tests.csproj
src/Caching/Test/Microsoft.Python.Analysis.Caching.Tests.csproj
src/Core/Impl/Microsoft.Python.Core.csproj
src/Core/Test/Microsoft.Python.Core.Tests.csproj
src/LanguageServer/Impl/Microsoft.Python.LanguageServer.csproj
src/LanguageServer/Test/Microsoft.Python.LanguageServer.Tests.csproj
src/Parsing/Test/Microsoft.Python.Parsing.Tests.csproj

For #1776.
Newtonsoft JSON dep was mismatched between assemblies. Updating everything (globbing should match versions with .NET Core 3.0) to make sure we're consolidated.

Update NuGet deps and consolidate

---

src/LanguageServer/Impl/LanguageServer.Lifetime.cs

For #1776.
Send the workspace root URI as the scope of the workspace configuration request. This may be needed to pick up some workspace-specific configuration.

Send root URI as workspace/configuration scope

---

src/Parsing/Impl/Microsoft-Python-Parsing.nuspec

I thought I made this change, but not seeing it there.

Parsing nuspec was referencing old version of FileSystemClobbing

---

src/Analysis/Ast/Impl/Analyzer/AnalysisWalker.cs
src/Analysis/Ast/Impl/Analyzer/Handlers/LoopHandler.cs
src/Analysis/Ast/Test/ImportTests.cs

Fixes #1775.
Try and while blocks were being walked twice, producing double diagnostics for code inside, as well as a likely performance hit from doing the same thing twice.
Need to run some more tests to make sure this isn't a regression (since I'm effectively removing a whole lot of walking on very common syntactic blocks).

Do not double-walk try and while statement bodies

---

src/LanguageServer/Impl/Indexing/SymbolIndex.cs
src/LanguageServer/Test/SymbolIndexTests.cs

Fixes #697. Modified version of https://github.com/microsoft/python-language-server/issues/697#issuecomment-597587009 (with case insensitivity).

Add loose fuzzy matching for workspace symbol queries

---

src/Core/Impl/IO/PathUtils.cs
src/LanguageServer/Impl/Implementation/Server.cs
src/LanguageServer/Impl/Resources.Designer.cs
src/LanguageServer/Impl/Resources.resx

If no interpreter is specified, fall back to finding the first `python` binary in `PATH`. This should eliminate the last "required" initialization option.
@MoerkerkeLander, I'd appreciate it if you could try this build.
Updates #1938.
Fixes #469.

Look into PATH for python if not provided in initialization options

---

src/LanguageServer/Impl/Indexing/SymbolIndexWalker.cs
src/LanguageServer/Test/SymbolIndexWalkerTests.cs

Don't walk imports when indexing symbols. I did this originally to match the old behavior, but it's not very useful for the outline to be cluttered with imports and this matches the behavior of other languages.
Not urgent to merge (want someone to see how this looks in the outline), but wanted to have this available.
Closes #612.
Fixes #1931.

Remove imports from symbols
